module ReviewConfig exposing (config)

{-| Static review for Magnes. `elm-review` catches by rule what would otherwise be caught
by reading: exports nothing imports, values nothing evaluates, and expressions with a
simpler equivalent.

`NoMissingTypeAnnotationInLetIn` is deliberately absent: this codebase does not annotate
`let` bindings, and enabling it would report 45 pre-existing sites rather than find
anything. Top-level annotations are still required.

`src/Magnes/Api` is generated by `elm-graphql` and regenerating it overwrites any change,
so it is exempt from everything. It exposes far more of bitmagnet's schema than Magnes
calls, which would otherwise drown the report in unused-export reports for code that is
build output.

-}

import NoExposingEverything
import NoImportingEverything
import NoMissingTypeAnnotation
import NoUnused.CustomTypeConstructorArgs
import NoUnused.CustomTypeConstructors
import NoUnused.Dependencies
import NoUnused.Exports
import NoUnused.Parameters
import NoUnused.Patterns
import NoUnused.Variables
import Review.Rule exposing (Rule)
import Simplify


config : List Rule
config =
    [ NoExposingEverything.rule
    , NoImportingEverything.rule []
    , NoMissingTypeAnnotation.rule
    , NoUnused.CustomTypeConstructors.rule []
    , NoUnused.CustomTypeConstructorArgs.rule
    , NoUnused.Dependencies.rule
    , NoUnused.Exports.rule
    , NoUnused.Parameters.rule
    , NoUnused.Patterns.rule
    , NoUnused.Variables.rule
    , Simplify.rule Simplify.defaults
    ]
        |> List.map (Review.Rule.ignoreErrorsForDirectories [ "src/Magnes/Api" ])
