-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.InputObject exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.ContentType
import Magnes.Api.Enum.FacetLogic
import Magnes.Api.Enum.FileType
import Magnes.Api.Enum.Language
import Magnes.Api.Enum.MetricsBucketDuration
import Magnes.Api.Enum.QueueJobStatus
import Magnes.Api.Enum.QueueJobsOrderByField
import Magnes.Api.Enum.TorrentContentOrderByField
import Magnes.Api.Enum.TorrentFilesOrderByField
import Magnes.Api.Enum.VideoResolution
import Magnes.Api.Enum.VideoSource
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


buildContentTypeFacetInput :
    (ContentTypeFacetInputOptionalFields -> ContentTypeFacetInputOptionalFields)
    -> ContentTypeFacetInput
buildContentTypeFacetInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { aggregate = Absent, filter = Absent }
    in
    { aggregate = optionals____.aggregate, filter = optionals____.filter }


type alias ContentTypeFacetInputOptionalFields =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List (Maybe Magnes.Api.Enum.ContentType.ContentType))
    }


{-| Type for the ContentTypeFacetInput input object.
-}
type alias ContentTypeFacetInput =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List (Maybe Magnes.Api.Enum.ContentType.ContentType))
    }


{-| Encode a ContentTypeFacetInput into a value that can be used as an argument.
-}
encodeContentTypeFacetInput : ContentTypeFacetInput -> Value
encodeContentTypeFacetInput input____ =
    Encode.maybeObject
        [ ( "aggregate", Encode.bool |> Encode.optional input____.aggregate ), ( "filter", (Encode.enum Magnes.Api.Enum.ContentType.toString |> Encode.maybe |> Encode.list) |> Encode.optional input____.filter ) ]


buildGenreFacetInput :
    (GenreFacetInputOptionalFields -> GenreFacetInputOptionalFields)
    -> GenreFacetInput
buildGenreFacetInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { aggregate = Absent, logic = Absent, filter = Absent }
    in
    { aggregate = optionals____.aggregate, logic = optionals____.logic, filter = optionals____.filter }


type alias GenreFacetInputOptionalFields =
    { aggregate : OptionalArgument Bool
    , logic : OptionalArgument Magnes.Api.Enum.FacetLogic.FacetLogic
    , filter : OptionalArgument (List String)
    }


{-| Type for the GenreFacetInput input object.
-}
type alias GenreFacetInput =
    { aggregate : OptionalArgument Bool
    , logic : OptionalArgument Magnes.Api.Enum.FacetLogic.FacetLogic
    , filter : OptionalArgument (List String)
    }


{-| Encode a GenreFacetInput into a value that can be used as an argument.
-}
encodeGenreFacetInput : GenreFacetInput -> Value
encodeGenreFacetInput input____ =
    Encode.maybeObject
        [ ( "aggregate", Encode.bool |> Encode.optional input____.aggregate ), ( "logic", Encode.enum Magnes.Api.Enum.FacetLogic.toString |> Encode.optional input____.logic ), ( "filter", (Encode.string |> Encode.list) |> Encode.optional input____.filter ) ]


buildLanguageFacetInput :
    (LanguageFacetInputOptionalFields -> LanguageFacetInputOptionalFields)
    -> LanguageFacetInput
buildLanguageFacetInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { aggregate = Absent, filter = Absent }
    in
    { aggregate = optionals____.aggregate, filter = optionals____.filter }


type alias LanguageFacetInputOptionalFields =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List Magnes.Api.Enum.Language.Language)
    }


{-| Type for the LanguageFacetInput input object.
-}
type alias LanguageFacetInput =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List Magnes.Api.Enum.Language.Language)
    }


{-| Encode a LanguageFacetInput into a value that can be used as an argument.
-}
encodeLanguageFacetInput : LanguageFacetInput -> Value
encodeLanguageFacetInput input____ =
    Encode.maybeObject
        [ ( "aggregate", Encode.bool |> Encode.optional input____.aggregate ), ( "filter", (Encode.enum Magnes.Api.Enum.Language.toString |> Encode.list) |> Encode.optional input____.filter ) ]


buildQueueEnqueueReprocessTorrentsBatchInput :
    (QueueEnqueueReprocessTorrentsBatchInputOptionalFields -> QueueEnqueueReprocessTorrentsBatchInputOptionalFields)
    -> QueueEnqueueReprocessTorrentsBatchInput
buildQueueEnqueueReprocessTorrentsBatchInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { purge = Absent, batchSize = Absent, chunkSize = Absent, contentTypes = Absent, orphans = Absent, classifierRematch = Absent, classifierWorkflow = Absent, apisDisabled = Absent, localSearchDisabled = Absent }
    in
    { purge = optionals____.purge, batchSize = optionals____.batchSize, chunkSize = optionals____.chunkSize, contentTypes = optionals____.contentTypes, orphans = optionals____.orphans, classifierRematch = optionals____.classifierRematch, classifierWorkflow = optionals____.classifierWorkflow, apisDisabled = optionals____.apisDisabled, localSearchDisabled = optionals____.localSearchDisabled }


type alias QueueEnqueueReprocessTorrentsBatchInputOptionalFields =
    { purge : OptionalArgument Bool
    , batchSize : OptionalArgument Int
    , chunkSize : OptionalArgument Int
    , contentTypes : OptionalArgument (List (Maybe Magnes.Api.Enum.ContentType.ContentType))
    , orphans : OptionalArgument Bool
    , classifierRematch : OptionalArgument Bool
    , classifierWorkflow : OptionalArgument String
    , apisDisabled : OptionalArgument Bool
    , localSearchDisabled : OptionalArgument Bool
    }


{-| Type for the QueueEnqueueReprocessTorrentsBatchInput input object.
-}
type alias QueueEnqueueReprocessTorrentsBatchInput =
    { purge : OptionalArgument Bool
    , batchSize : OptionalArgument Int
    , chunkSize : OptionalArgument Int
    , contentTypes : OptionalArgument (List (Maybe Magnes.Api.Enum.ContentType.ContentType))
    , orphans : OptionalArgument Bool
    , classifierRematch : OptionalArgument Bool
    , classifierWorkflow : OptionalArgument String
    , apisDisabled : OptionalArgument Bool
    , localSearchDisabled : OptionalArgument Bool
    }


{-| Encode a QueueEnqueueReprocessTorrentsBatchInput into a value that can be used as an argument.
-}
encodeQueueEnqueueReprocessTorrentsBatchInput : QueueEnqueueReprocessTorrentsBatchInput -> Value
encodeQueueEnqueueReprocessTorrentsBatchInput input____ =
    Encode.maybeObject
        [ ( "purge", Encode.bool |> Encode.optional input____.purge ), ( "batchSize", Encode.int |> Encode.optional input____.batchSize ), ( "chunkSize", Encode.int |> Encode.optional input____.chunkSize ), ( "contentTypes", (Encode.enum Magnes.Api.Enum.ContentType.toString |> Encode.maybe |> Encode.list) |> Encode.optional input____.contentTypes ), ( "orphans", Encode.bool |> Encode.optional input____.orphans ), ( "classifierRematch", Encode.bool |> Encode.optional input____.classifierRematch ), ( "classifierWorkflow", Encode.string |> Encode.optional input____.classifierWorkflow ), ( "apisDisabled", Encode.bool |> Encode.optional input____.apisDisabled ), ( "localSearchDisabled", Encode.bool |> Encode.optional input____.localSearchDisabled ) ]


buildQueueJobQueueFacetInput :
    (QueueJobQueueFacetInputOptionalFields -> QueueJobQueueFacetInputOptionalFields)
    -> QueueJobQueueFacetInput
buildQueueJobQueueFacetInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { aggregate = Absent, filter = Absent }
    in
    { aggregate = optionals____.aggregate, filter = optionals____.filter }


type alias QueueJobQueueFacetInputOptionalFields =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List String)
    }


{-| Type for the QueueJobQueueFacetInput input object.
-}
type alias QueueJobQueueFacetInput =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List String)
    }


{-| Encode a QueueJobQueueFacetInput into a value that can be used as an argument.
-}
encodeQueueJobQueueFacetInput : QueueJobQueueFacetInput -> Value
encodeQueueJobQueueFacetInput input____ =
    Encode.maybeObject
        [ ( "aggregate", Encode.bool |> Encode.optional input____.aggregate ), ( "filter", (Encode.string |> Encode.list) |> Encode.optional input____.filter ) ]


buildQueueJobStatusFacetInput :
    (QueueJobStatusFacetInputOptionalFields -> QueueJobStatusFacetInputOptionalFields)
    -> QueueJobStatusFacetInput
buildQueueJobStatusFacetInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { aggregate = Absent, filter = Absent }
    in
    { aggregate = optionals____.aggregate, filter = optionals____.filter }


type alias QueueJobStatusFacetInputOptionalFields =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List Magnes.Api.Enum.QueueJobStatus.QueueJobStatus)
    }


{-| Type for the QueueJobStatusFacetInput input object.
-}
type alias QueueJobStatusFacetInput =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List Magnes.Api.Enum.QueueJobStatus.QueueJobStatus)
    }


{-| Encode a QueueJobStatusFacetInput into a value that can be used as an argument.
-}
encodeQueueJobStatusFacetInput : QueueJobStatusFacetInput -> Value
encodeQueueJobStatusFacetInput input____ =
    Encode.maybeObject
        [ ( "aggregate", Encode.bool |> Encode.optional input____.aggregate ), ( "filter", (Encode.enum Magnes.Api.Enum.QueueJobStatus.toString |> Encode.list) |> Encode.optional input____.filter ) ]


buildQueueJobsFacetsInput :
    (QueueJobsFacetsInputOptionalFields -> QueueJobsFacetsInputOptionalFields)
    -> QueueJobsFacetsInput
buildQueueJobsFacetsInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { status = Absent, queue = Absent }
    in
    { status = optionals____.status, queue = optionals____.queue }


type alias QueueJobsFacetsInputOptionalFields =
    { status : OptionalArgument QueueJobStatusFacetInput
    , queue : OptionalArgument QueueJobQueueFacetInput
    }


{-| Type for the QueueJobsFacetsInput input object.
-}
type alias QueueJobsFacetsInput =
    { status : OptionalArgument QueueJobStatusFacetInput
    , queue : OptionalArgument QueueJobQueueFacetInput
    }


{-| Encode a QueueJobsFacetsInput into a value that can be used as an argument.
-}
encodeQueueJobsFacetsInput : QueueJobsFacetsInput -> Value
encodeQueueJobsFacetsInput input____ =
    Encode.maybeObject
        [ ( "status", encodeQueueJobStatusFacetInput |> Encode.optional input____.status ), ( "queue", encodeQueueJobQueueFacetInput |> Encode.optional input____.queue ) ]


buildQueueJobsOrderByInput :
    QueueJobsOrderByInputRequiredFields
    -> (QueueJobsOrderByInputOptionalFields -> QueueJobsOrderByInputOptionalFields)
    -> QueueJobsOrderByInput
buildQueueJobsOrderByInput required____ fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { descending = Absent }
    in
    { field = required____.field, descending = optionals____.descending }


type alias QueueJobsOrderByInputRequiredFields =
    { field : Magnes.Api.Enum.QueueJobsOrderByField.QueueJobsOrderByField }


type alias QueueJobsOrderByInputOptionalFields =
    { descending : OptionalArgument Bool }


{-| Type for the QueueJobsOrderByInput input object.
-}
type alias QueueJobsOrderByInput =
    { field : Magnes.Api.Enum.QueueJobsOrderByField.QueueJobsOrderByField
    , descending : OptionalArgument Bool
    }


{-| Encode a QueueJobsOrderByInput into a value that can be used as an argument.
-}
encodeQueueJobsOrderByInput : QueueJobsOrderByInput -> Value
encodeQueueJobsOrderByInput input____ =
    Encode.maybeObject
        [ ( "field", Encode.enum Magnes.Api.Enum.QueueJobsOrderByField.toString input____.field |> Just ), ( "descending", Encode.bool |> Encode.optional input____.descending ) ]


buildQueueJobsQueryInput :
    (QueueJobsQueryInputOptionalFields -> QueueJobsQueryInputOptionalFields)
    -> QueueJobsQueryInput
buildQueueJobsQueryInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { queues = Absent, statuses = Absent, limit = Absent, page = Absent, offset = Absent, totalCount = Absent, hasNextPage = Absent, facets = Absent, orderBy = Absent }
    in
    { queues = optionals____.queues, statuses = optionals____.statuses, limit = optionals____.limit, page = optionals____.page, offset = optionals____.offset, totalCount = optionals____.totalCount, hasNextPage = optionals____.hasNextPage, facets = optionals____.facets, orderBy = optionals____.orderBy }


type alias QueueJobsQueryInputOptionalFields =
    { queues : OptionalArgument (List String)
    , statuses : OptionalArgument (List Magnes.Api.Enum.QueueJobStatus.QueueJobStatus)
    , limit : OptionalArgument Int
    , page : OptionalArgument Int
    , offset : OptionalArgument Int
    , totalCount : OptionalArgument Bool
    , hasNextPage : OptionalArgument Bool
    , facets : OptionalArgument QueueJobsFacetsInput
    , orderBy : OptionalArgument (List QueueJobsOrderByInput)
    }


{-| Type for the QueueJobsQueryInput input object.
-}
type alias QueueJobsQueryInput =
    { queues : OptionalArgument (List String)
    , statuses : OptionalArgument (List Magnes.Api.Enum.QueueJobStatus.QueueJobStatus)
    , limit : OptionalArgument Int
    , page : OptionalArgument Int
    , offset : OptionalArgument Int
    , totalCount : OptionalArgument Bool
    , hasNextPage : OptionalArgument Bool
    , facets : OptionalArgument QueueJobsFacetsInput
    , orderBy : OptionalArgument (List QueueJobsOrderByInput)
    }


{-| Encode a QueueJobsQueryInput into a value that can be used as an argument.
-}
encodeQueueJobsQueryInput : QueueJobsQueryInput -> Value
encodeQueueJobsQueryInput input____ =
    Encode.maybeObject
        [ ( "queues", (Encode.string |> Encode.list) |> Encode.optional input____.queues ), ( "statuses", (Encode.enum Magnes.Api.Enum.QueueJobStatus.toString |> Encode.list) |> Encode.optional input____.statuses ), ( "limit", Encode.int |> Encode.optional input____.limit ), ( "page", Encode.int |> Encode.optional input____.page ), ( "offset", Encode.int |> Encode.optional input____.offset ), ( "totalCount", Encode.bool |> Encode.optional input____.totalCount ), ( "hasNextPage", Encode.bool |> Encode.optional input____.hasNextPage ), ( "facets", encodeQueueJobsFacetsInput |> Encode.optional input____.facets ), ( "orderBy", (encodeQueueJobsOrderByInput |> Encode.list) |> Encode.optional input____.orderBy ) ]


buildQueueMetricsQueryInput :
    QueueMetricsQueryInputRequiredFields
    -> (QueueMetricsQueryInputOptionalFields -> QueueMetricsQueryInputOptionalFields)
    -> QueueMetricsQueryInput
buildQueueMetricsQueryInput required____ fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { statuses = Absent, queues = Absent, startTime = Absent, endTime = Absent }
    in
    { bucketDuration = required____.bucketDuration, statuses = optionals____.statuses, queues = optionals____.queues, startTime = optionals____.startTime, endTime = optionals____.endTime }


type alias QueueMetricsQueryInputRequiredFields =
    { bucketDuration : Magnes.Api.Enum.MetricsBucketDuration.MetricsBucketDuration }


type alias QueueMetricsQueryInputOptionalFields =
    { statuses : OptionalArgument (List Magnes.Api.Enum.QueueJobStatus.QueueJobStatus)
    , queues : OptionalArgument (List String)
    , startTime : OptionalArgument Magnes.Api.ScalarCodecs.DateTime
    , endTime : OptionalArgument Magnes.Api.ScalarCodecs.DateTime
    }


{-| Type for the QueueMetricsQueryInput input object.
-}
type alias QueueMetricsQueryInput =
    { bucketDuration : Magnes.Api.Enum.MetricsBucketDuration.MetricsBucketDuration
    , statuses : OptionalArgument (List Magnes.Api.Enum.QueueJobStatus.QueueJobStatus)
    , queues : OptionalArgument (List String)
    , startTime : OptionalArgument Magnes.Api.ScalarCodecs.DateTime
    , endTime : OptionalArgument Magnes.Api.ScalarCodecs.DateTime
    }


{-| Encode a QueueMetricsQueryInput into a value that can be used as an argument.
-}
encodeQueueMetricsQueryInput : QueueMetricsQueryInput -> Value
encodeQueueMetricsQueryInput input____ =
    Encode.maybeObject
        [ ( "bucketDuration", Encode.enum Magnes.Api.Enum.MetricsBucketDuration.toString input____.bucketDuration |> Just ), ( "statuses", (Encode.enum Magnes.Api.Enum.QueueJobStatus.toString |> Encode.list) |> Encode.optional input____.statuses ), ( "queues", (Encode.string |> Encode.list) |> Encode.optional input____.queues ), ( "startTime", (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapEncoder .codecDateTime) |> Encode.optional input____.startTime ), ( "endTime", (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapEncoder .codecDateTime) |> Encode.optional input____.endTime ) ]


buildQueuePurgeJobsInput :
    (QueuePurgeJobsInputOptionalFields -> QueuePurgeJobsInputOptionalFields)
    -> QueuePurgeJobsInput
buildQueuePurgeJobsInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { queues = Absent, statuses = Absent }
    in
    { queues = optionals____.queues, statuses = optionals____.statuses }


type alias QueuePurgeJobsInputOptionalFields =
    { queues : OptionalArgument (List String)
    , statuses : OptionalArgument (List Magnes.Api.Enum.QueueJobStatus.QueueJobStatus)
    }


{-| Type for the QueuePurgeJobsInput input object.
-}
type alias QueuePurgeJobsInput =
    { queues : OptionalArgument (List String)
    , statuses : OptionalArgument (List Magnes.Api.Enum.QueueJobStatus.QueueJobStatus)
    }


{-| Encode a QueuePurgeJobsInput into a value that can be used as an argument.
-}
encodeQueuePurgeJobsInput : QueuePurgeJobsInput -> Value
encodeQueuePurgeJobsInput input____ =
    Encode.maybeObject
        [ ( "queues", (Encode.string |> Encode.list) |> Encode.optional input____.queues ), ( "statuses", (Encode.enum Magnes.Api.Enum.QueueJobStatus.toString |> Encode.list) |> Encode.optional input____.statuses ) ]


buildReleaseYearFacetInput :
    (ReleaseYearFacetInputOptionalFields -> ReleaseYearFacetInputOptionalFields)
    -> ReleaseYearFacetInput
buildReleaseYearFacetInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { aggregate = Absent, filter = Absent }
    in
    { aggregate = optionals____.aggregate, filter = optionals____.filter }


type alias ReleaseYearFacetInputOptionalFields =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List (Maybe Magnes.Api.ScalarCodecs.Year))
    }


{-| Type for the ReleaseYearFacetInput input object.
-}
type alias ReleaseYearFacetInput =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List (Maybe Magnes.Api.ScalarCodecs.Year))
    }


{-| Encode a ReleaseYearFacetInput into a value that can be used as an argument.
-}
encodeReleaseYearFacetInput : ReleaseYearFacetInput -> Value
encodeReleaseYearFacetInput input____ =
    Encode.maybeObject
        [ ( "aggregate", Encode.bool |> Encode.optional input____.aggregate ), ( "filter", ((Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapEncoder .codecYear) |> Encode.maybe |> Encode.list) |> Encode.optional input____.filter ) ]


buildSuggestTagsQueryInput :
    (SuggestTagsQueryInputOptionalFields -> SuggestTagsQueryInputOptionalFields)
    -> SuggestTagsQueryInput
buildSuggestTagsQueryInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { prefix = Absent, exclusions = Absent }
    in
    { prefix = optionals____.prefix, exclusions = optionals____.exclusions }


type alias SuggestTagsQueryInputOptionalFields =
    { prefix : OptionalArgument String
    , exclusions : OptionalArgument (List String)
    }


{-| Type for the SuggestTagsQueryInput input object.
-}
type alias SuggestTagsQueryInput =
    { prefix : OptionalArgument String
    , exclusions : OptionalArgument (List String)
    }


{-| Encode a SuggestTagsQueryInput into a value that can be used as an argument.
-}
encodeSuggestTagsQueryInput : SuggestTagsQueryInput -> Value
encodeSuggestTagsQueryInput input____ =
    Encode.maybeObject
        [ ( "prefix", Encode.string |> Encode.optional input____.prefix ), ( "exclusions", (Encode.string |> Encode.list) |> Encode.optional input____.exclusions ) ]


buildTorrentContentFacetsInput :
    (TorrentContentFacetsInputOptionalFields -> TorrentContentFacetsInputOptionalFields)
    -> TorrentContentFacetsInput
buildTorrentContentFacetsInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { contentType = Absent, torrentSource = Absent, torrentTag = Absent, torrentFileType = Absent, language = Absent, genre = Absent, releaseYear = Absent, videoResolution = Absent, videoSource = Absent }
    in
    { contentType = optionals____.contentType, torrentSource = optionals____.torrentSource, torrentTag = optionals____.torrentTag, torrentFileType = optionals____.torrentFileType, language = optionals____.language, genre = optionals____.genre, releaseYear = optionals____.releaseYear, videoResolution = optionals____.videoResolution, videoSource = optionals____.videoSource }


type alias TorrentContentFacetsInputOptionalFields =
    { contentType : OptionalArgument ContentTypeFacetInput
    , torrentSource : OptionalArgument TorrentSourceFacetInput
    , torrentTag : OptionalArgument TorrentTagFacetInput
    , torrentFileType : OptionalArgument TorrentFileTypeFacetInput
    , language : OptionalArgument LanguageFacetInput
    , genre : OptionalArgument GenreFacetInput
    , releaseYear : OptionalArgument ReleaseYearFacetInput
    , videoResolution : OptionalArgument VideoResolutionFacetInput
    , videoSource : OptionalArgument VideoSourceFacetInput
    }


{-| Type for the TorrentContentFacetsInput input object.
-}
type alias TorrentContentFacetsInput =
    { contentType : OptionalArgument ContentTypeFacetInput
    , torrentSource : OptionalArgument TorrentSourceFacetInput
    , torrentTag : OptionalArgument TorrentTagFacetInput
    , torrentFileType : OptionalArgument TorrentFileTypeFacetInput
    , language : OptionalArgument LanguageFacetInput
    , genre : OptionalArgument GenreFacetInput
    , releaseYear : OptionalArgument ReleaseYearFacetInput
    , videoResolution : OptionalArgument VideoResolutionFacetInput
    , videoSource : OptionalArgument VideoSourceFacetInput
    }


{-| Encode a TorrentContentFacetsInput into a value that can be used as an argument.
-}
encodeTorrentContentFacetsInput : TorrentContentFacetsInput -> Value
encodeTorrentContentFacetsInput input____ =
    Encode.maybeObject
        [ ( "contentType", encodeContentTypeFacetInput |> Encode.optional input____.contentType ), ( "torrentSource", encodeTorrentSourceFacetInput |> Encode.optional input____.torrentSource ), ( "torrentTag", encodeTorrentTagFacetInput |> Encode.optional input____.torrentTag ), ( "torrentFileType", encodeTorrentFileTypeFacetInput |> Encode.optional input____.torrentFileType ), ( "language", encodeLanguageFacetInput |> Encode.optional input____.language ), ( "genre", encodeGenreFacetInput |> Encode.optional input____.genre ), ( "releaseYear", encodeReleaseYearFacetInput |> Encode.optional input____.releaseYear ), ( "videoResolution", encodeVideoResolutionFacetInput |> Encode.optional input____.videoResolution ), ( "videoSource", encodeVideoSourceFacetInput |> Encode.optional input____.videoSource ) ]


buildTorrentContentOrderByInput :
    TorrentContentOrderByInputRequiredFields
    -> (TorrentContentOrderByInputOptionalFields -> TorrentContentOrderByInputOptionalFields)
    -> TorrentContentOrderByInput
buildTorrentContentOrderByInput required____ fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { descending = Absent }
    in
    { field = required____.field, descending = optionals____.descending }


type alias TorrentContentOrderByInputRequiredFields =
    { field : Magnes.Api.Enum.TorrentContentOrderByField.TorrentContentOrderByField }


type alias TorrentContentOrderByInputOptionalFields =
    { descending : OptionalArgument Bool }


{-| Type for the TorrentContentOrderByInput input object.
-}
type alias TorrentContentOrderByInput =
    { field : Magnes.Api.Enum.TorrentContentOrderByField.TorrentContentOrderByField
    , descending : OptionalArgument Bool
    }


{-| Encode a TorrentContentOrderByInput into a value that can be used as an argument.
-}
encodeTorrentContentOrderByInput : TorrentContentOrderByInput -> Value
encodeTorrentContentOrderByInput input____ =
    Encode.maybeObject
        [ ( "field", Encode.enum Magnes.Api.Enum.TorrentContentOrderByField.toString input____.field |> Just ), ( "descending", Encode.bool |> Encode.optional input____.descending ) ]


buildTorrentContentSearchQueryInput :
    (TorrentContentSearchQueryInputOptionalFields -> TorrentContentSearchQueryInputOptionalFields)
    -> TorrentContentSearchQueryInput
buildTorrentContentSearchQueryInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { queryString = Absent, limit = Absent, page = Absent, offset = Absent, totalCount = Absent, hasNextPage = Absent, infoHashes = Absent, facets = Absent, orderBy = Absent, cached = Absent, aggregationBudget = Absent }
    in
    { queryString = optionals____.queryString, limit = optionals____.limit, page = optionals____.page, offset = optionals____.offset, totalCount = optionals____.totalCount, hasNextPage = optionals____.hasNextPage, infoHashes = optionals____.infoHashes, facets = optionals____.facets, orderBy = optionals____.orderBy, cached = optionals____.cached, aggregationBudget = optionals____.aggregationBudget }


type alias TorrentContentSearchQueryInputOptionalFields =
    { queryString : OptionalArgument String
    , limit : OptionalArgument Int
    , page : OptionalArgument Int
    , offset : OptionalArgument Int
    , totalCount : OptionalArgument Bool
    , hasNextPage : OptionalArgument Bool
    , infoHashes : OptionalArgument (List Magnes.Api.ScalarCodecs.Hash20)
    , facets : OptionalArgument TorrentContentFacetsInput
    , orderBy : OptionalArgument (List TorrentContentOrderByInput)
    , cached : OptionalArgument Bool
    , aggregationBudget : OptionalArgument Float
    }


{-| Type for the TorrentContentSearchQueryInput input object.
-}
type alias TorrentContentSearchQueryInput =
    { queryString : OptionalArgument String
    , limit : OptionalArgument Int
    , page : OptionalArgument Int
    , offset : OptionalArgument Int
    , totalCount : OptionalArgument Bool
    , hasNextPage : OptionalArgument Bool
    , infoHashes : OptionalArgument (List Magnes.Api.ScalarCodecs.Hash20)
    , facets : OptionalArgument TorrentContentFacetsInput
    , orderBy : OptionalArgument (List TorrentContentOrderByInput)
    , cached : OptionalArgument Bool
    , aggregationBudget : OptionalArgument Float
    }


{-| Encode a TorrentContentSearchQueryInput into a value that can be used as an argument.
-}
encodeTorrentContentSearchQueryInput : TorrentContentSearchQueryInput -> Value
encodeTorrentContentSearchQueryInput input____ =
    Encode.maybeObject
        [ ( "queryString", Encode.string |> Encode.optional input____.queryString ), ( "limit", Encode.int |> Encode.optional input____.limit ), ( "page", Encode.int |> Encode.optional input____.page ), ( "offset", Encode.int |> Encode.optional input____.offset ), ( "totalCount", Encode.bool |> Encode.optional input____.totalCount ), ( "hasNextPage", Encode.bool |> Encode.optional input____.hasNextPage ), ( "infoHashes", ((Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapEncoder .codecHash20) |> Encode.list) |> Encode.optional input____.infoHashes ), ( "facets", encodeTorrentContentFacetsInput |> Encode.optional input____.facets ), ( "orderBy", (encodeTorrentContentOrderByInput |> Encode.list) |> Encode.optional input____.orderBy ), ( "cached", Encode.bool |> Encode.optional input____.cached ), ( "aggregationBudget", Encode.float |> Encode.optional input____.aggregationBudget ) ]


buildTorrentFileTypeFacetInput :
    (TorrentFileTypeFacetInputOptionalFields -> TorrentFileTypeFacetInputOptionalFields)
    -> TorrentFileTypeFacetInput
buildTorrentFileTypeFacetInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { aggregate = Absent, logic = Absent, filter = Absent }
    in
    { aggregate = optionals____.aggregate, logic = optionals____.logic, filter = optionals____.filter }


type alias TorrentFileTypeFacetInputOptionalFields =
    { aggregate : OptionalArgument Bool
    , logic : OptionalArgument Magnes.Api.Enum.FacetLogic.FacetLogic
    , filter : OptionalArgument (List Magnes.Api.Enum.FileType.FileType)
    }


{-| Type for the TorrentFileTypeFacetInput input object.
-}
type alias TorrentFileTypeFacetInput =
    { aggregate : OptionalArgument Bool
    , logic : OptionalArgument Magnes.Api.Enum.FacetLogic.FacetLogic
    , filter : OptionalArgument (List Magnes.Api.Enum.FileType.FileType)
    }


{-| Encode a TorrentFileTypeFacetInput into a value that can be used as an argument.
-}
encodeTorrentFileTypeFacetInput : TorrentFileTypeFacetInput -> Value
encodeTorrentFileTypeFacetInput input____ =
    Encode.maybeObject
        [ ( "aggregate", Encode.bool |> Encode.optional input____.aggregate ), ( "logic", Encode.enum Magnes.Api.Enum.FacetLogic.toString |> Encode.optional input____.logic ), ( "filter", (Encode.enum Magnes.Api.Enum.FileType.toString |> Encode.list) |> Encode.optional input____.filter ) ]


buildTorrentFilesOrderByInput :
    TorrentFilesOrderByInputRequiredFields
    -> (TorrentFilesOrderByInputOptionalFields -> TorrentFilesOrderByInputOptionalFields)
    -> TorrentFilesOrderByInput
buildTorrentFilesOrderByInput required____ fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { descending = Absent }
    in
    { field = required____.field, descending = optionals____.descending }


type alias TorrentFilesOrderByInputRequiredFields =
    { field : Magnes.Api.Enum.TorrentFilesOrderByField.TorrentFilesOrderByField }


type alias TorrentFilesOrderByInputOptionalFields =
    { descending : OptionalArgument Bool }


{-| Type for the TorrentFilesOrderByInput input object.
-}
type alias TorrentFilesOrderByInput =
    { field : Magnes.Api.Enum.TorrentFilesOrderByField.TorrentFilesOrderByField
    , descending : OptionalArgument Bool
    }


{-| Encode a TorrentFilesOrderByInput into a value that can be used as an argument.
-}
encodeTorrentFilesOrderByInput : TorrentFilesOrderByInput -> Value
encodeTorrentFilesOrderByInput input____ =
    Encode.maybeObject
        [ ( "field", Encode.enum Magnes.Api.Enum.TorrentFilesOrderByField.toString input____.field |> Just ), ( "descending", Encode.bool |> Encode.optional input____.descending ) ]


buildTorrentFilesQueryInput :
    (TorrentFilesQueryInputOptionalFields -> TorrentFilesQueryInputOptionalFields)
    -> TorrentFilesQueryInput
buildTorrentFilesQueryInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { limit = Absent, page = Absent, offset = Absent, totalCount = Absent, hasNextPage = Absent, infoHashes = Absent, orderBy = Absent, cached = Absent }
    in
    { limit = optionals____.limit, page = optionals____.page, offset = optionals____.offset, totalCount = optionals____.totalCount, hasNextPage = optionals____.hasNextPage, infoHashes = optionals____.infoHashes, orderBy = optionals____.orderBy, cached = optionals____.cached }


type alias TorrentFilesQueryInputOptionalFields =
    { limit : OptionalArgument Int
    , page : OptionalArgument Int
    , offset : OptionalArgument Int
    , totalCount : OptionalArgument Bool
    , hasNextPage : OptionalArgument Bool
    , infoHashes : OptionalArgument (List Magnes.Api.ScalarCodecs.Hash20)
    , orderBy : OptionalArgument (List TorrentFilesOrderByInput)
    , cached : OptionalArgument Bool
    }


{-| Type for the TorrentFilesQueryInput input object.
-}
type alias TorrentFilesQueryInput =
    { limit : OptionalArgument Int
    , page : OptionalArgument Int
    , offset : OptionalArgument Int
    , totalCount : OptionalArgument Bool
    , hasNextPage : OptionalArgument Bool
    , infoHashes : OptionalArgument (List Magnes.Api.ScalarCodecs.Hash20)
    , orderBy : OptionalArgument (List TorrentFilesOrderByInput)
    , cached : OptionalArgument Bool
    }


{-| Encode a TorrentFilesQueryInput into a value that can be used as an argument.
-}
encodeTorrentFilesQueryInput : TorrentFilesQueryInput -> Value
encodeTorrentFilesQueryInput input____ =
    Encode.maybeObject
        [ ( "limit", Encode.int |> Encode.optional input____.limit ), ( "page", Encode.int |> Encode.optional input____.page ), ( "offset", Encode.int |> Encode.optional input____.offset ), ( "totalCount", Encode.bool |> Encode.optional input____.totalCount ), ( "hasNextPage", Encode.bool |> Encode.optional input____.hasNextPage ), ( "infoHashes", ((Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapEncoder .codecHash20) |> Encode.list) |> Encode.optional input____.infoHashes ), ( "orderBy", (encodeTorrentFilesOrderByInput |> Encode.list) |> Encode.optional input____.orderBy ), ( "cached", Encode.bool |> Encode.optional input____.cached ) ]


buildTorrentMetricsQueryInput :
    TorrentMetricsQueryInputRequiredFields
    -> (TorrentMetricsQueryInputOptionalFields -> TorrentMetricsQueryInputOptionalFields)
    -> TorrentMetricsQueryInput
buildTorrentMetricsQueryInput required____ fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { sources = Absent, startTime = Absent, endTime = Absent }
    in
    { bucketDuration = required____.bucketDuration, sources = optionals____.sources, startTime = optionals____.startTime, endTime = optionals____.endTime }


type alias TorrentMetricsQueryInputRequiredFields =
    { bucketDuration : Magnes.Api.Enum.MetricsBucketDuration.MetricsBucketDuration }


type alias TorrentMetricsQueryInputOptionalFields =
    { sources : OptionalArgument (List String)
    , startTime : OptionalArgument Magnes.Api.ScalarCodecs.DateTime
    , endTime : OptionalArgument Magnes.Api.ScalarCodecs.DateTime
    }


{-| Type for the TorrentMetricsQueryInput input object.
-}
type alias TorrentMetricsQueryInput =
    { bucketDuration : Magnes.Api.Enum.MetricsBucketDuration.MetricsBucketDuration
    , sources : OptionalArgument (List String)
    , startTime : OptionalArgument Magnes.Api.ScalarCodecs.DateTime
    , endTime : OptionalArgument Magnes.Api.ScalarCodecs.DateTime
    }


{-| Encode a TorrentMetricsQueryInput into a value that can be used as an argument.
-}
encodeTorrentMetricsQueryInput : TorrentMetricsQueryInput -> Value
encodeTorrentMetricsQueryInput input____ =
    Encode.maybeObject
        [ ( "bucketDuration", Encode.enum Magnes.Api.Enum.MetricsBucketDuration.toString input____.bucketDuration |> Just ), ( "sources", (Encode.string |> Encode.list) |> Encode.optional input____.sources ), ( "startTime", (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapEncoder .codecDateTime) |> Encode.optional input____.startTime ), ( "endTime", (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapEncoder .codecDateTime) |> Encode.optional input____.endTime ) ]


buildTorrentReprocessInput :
    TorrentReprocessInputRequiredFields
    -> (TorrentReprocessInputOptionalFields -> TorrentReprocessInputOptionalFields)
    -> TorrentReprocessInput
buildTorrentReprocessInput required____ fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { classifierRematch = Absent, classifierWorkflow = Absent, apisDisabled = Absent, localSearchDisabled = Absent }
    in
    { infoHashes = required____.infoHashes, classifierRematch = optionals____.classifierRematch, classifierWorkflow = optionals____.classifierWorkflow, apisDisabled = optionals____.apisDisabled, localSearchDisabled = optionals____.localSearchDisabled }


type alias TorrentReprocessInputRequiredFields =
    { infoHashes : List Magnes.Api.ScalarCodecs.Hash20 }


type alias TorrentReprocessInputOptionalFields =
    { classifierRematch : OptionalArgument Bool
    , classifierWorkflow : OptionalArgument String
    , apisDisabled : OptionalArgument Bool
    , localSearchDisabled : OptionalArgument Bool
    }


{-| Type for the TorrentReprocessInput input object.
-}
type alias TorrentReprocessInput =
    { infoHashes : List Magnes.Api.ScalarCodecs.Hash20
    , classifierRematch : OptionalArgument Bool
    , classifierWorkflow : OptionalArgument String
    , apisDisabled : OptionalArgument Bool
    , localSearchDisabled : OptionalArgument Bool
    }


{-| Encode a TorrentReprocessInput into a value that can be used as an argument.
-}
encodeTorrentReprocessInput : TorrentReprocessInput -> Value
encodeTorrentReprocessInput input____ =
    Encode.maybeObject
        [ ( "infoHashes", ((Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapEncoder .codecHash20) |> Encode.list) input____.infoHashes |> Just ), ( "classifierRematch", Encode.bool |> Encode.optional input____.classifierRematch ), ( "classifierWorkflow", Encode.string |> Encode.optional input____.classifierWorkflow ), ( "apisDisabled", Encode.bool |> Encode.optional input____.apisDisabled ), ( "localSearchDisabled", Encode.bool |> Encode.optional input____.localSearchDisabled ) ]


buildTorrentSourceFacetInput :
    (TorrentSourceFacetInputOptionalFields -> TorrentSourceFacetInputOptionalFields)
    -> TorrentSourceFacetInput
buildTorrentSourceFacetInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { aggregate = Absent, logic = Absent, filter = Absent }
    in
    { aggregate = optionals____.aggregate, logic = optionals____.logic, filter = optionals____.filter }


type alias TorrentSourceFacetInputOptionalFields =
    { aggregate : OptionalArgument Bool
    , logic : OptionalArgument Magnes.Api.Enum.FacetLogic.FacetLogic
    , filter : OptionalArgument (List String)
    }


{-| Type for the TorrentSourceFacetInput input object.
-}
type alias TorrentSourceFacetInput =
    { aggregate : OptionalArgument Bool
    , logic : OptionalArgument Magnes.Api.Enum.FacetLogic.FacetLogic
    , filter : OptionalArgument (List String)
    }


{-| Encode a TorrentSourceFacetInput into a value that can be used as an argument.
-}
encodeTorrentSourceFacetInput : TorrentSourceFacetInput -> Value
encodeTorrentSourceFacetInput input____ =
    Encode.maybeObject
        [ ( "aggregate", Encode.bool |> Encode.optional input____.aggregate ), ( "logic", Encode.enum Magnes.Api.Enum.FacetLogic.toString |> Encode.optional input____.logic ), ( "filter", (Encode.string |> Encode.list) |> Encode.optional input____.filter ) ]


buildTorrentTagFacetInput :
    (TorrentTagFacetInputOptionalFields -> TorrentTagFacetInputOptionalFields)
    -> TorrentTagFacetInput
buildTorrentTagFacetInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { aggregate = Absent, logic = Absent, filter = Absent }
    in
    { aggregate = optionals____.aggregate, logic = optionals____.logic, filter = optionals____.filter }


type alias TorrentTagFacetInputOptionalFields =
    { aggregate : OptionalArgument Bool
    , logic : OptionalArgument Magnes.Api.Enum.FacetLogic.FacetLogic
    , filter : OptionalArgument (List String)
    }


{-| Type for the TorrentTagFacetInput input object.
-}
type alias TorrentTagFacetInput =
    { aggregate : OptionalArgument Bool
    , logic : OptionalArgument Magnes.Api.Enum.FacetLogic.FacetLogic
    , filter : OptionalArgument (List String)
    }


{-| Encode a TorrentTagFacetInput into a value that can be used as an argument.
-}
encodeTorrentTagFacetInput : TorrentTagFacetInput -> Value
encodeTorrentTagFacetInput input____ =
    Encode.maybeObject
        [ ( "aggregate", Encode.bool |> Encode.optional input____.aggregate ), ( "logic", Encode.enum Magnes.Api.Enum.FacetLogic.toString |> Encode.optional input____.logic ), ( "filter", (Encode.string |> Encode.list) |> Encode.optional input____.filter ) ]


buildVideoResolutionFacetInput :
    (VideoResolutionFacetInputOptionalFields -> VideoResolutionFacetInputOptionalFields)
    -> VideoResolutionFacetInput
buildVideoResolutionFacetInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { aggregate = Absent, filter = Absent }
    in
    { aggregate = optionals____.aggregate, filter = optionals____.filter }


type alias VideoResolutionFacetInputOptionalFields =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List (Maybe Magnes.Api.Enum.VideoResolution.VideoResolution))
    }


{-| Type for the VideoResolutionFacetInput input object.
-}
type alias VideoResolutionFacetInput =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List (Maybe Magnes.Api.Enum.VideoResolution.VideoResolution))
    }


{-| Encode a VideoResolutionFacetInput into a value that can be used as an argument.
-}
encodeVideoResolutionFacetInput : VideoResolutionFacetInput -> Value
encodeVideoResolutionFacetInput input____ =
    Encode.maybeObject
        [ ( "aggregate", Encode.bool |> Encode.optional input____.aggregate ), ( "filter", (Encode.enum Magnes.Api.Enum.VideoResolution.toString |> Encode.maybe |> Encode.list) |> Encode.optional input____.filter ) ]


buildVideoSourceFacetInput :
    (VideoSourceFacetInputOptionalFields -> VideoSourceFacetInputOptionalFields)
    -> VideoSourceFacetInput
buildVideoSourceFacetInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { aggregate = Absent, filter = Absent }
    in
    { aggregate = optionals____.aggregate, filter = optionals____.filter }


type alias VideoSourceFacetInputOptionalFields =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List (Maybe Magnes.Api.Enum.VideoSource.VideoSource))
    }


{-| Type for the VideoSourceFacetInput input object.
-}
type alias VideoSourceFacetInput =
    { aggregate : OptionalArgument Bool
    , filter : OptionalArgument (List (Maybe Magnes.Api.Enum.VideoSource.VideoSource))
    }


{-| Encode a VideoSourceFacetInput into a value that can be used as an argument.
-}
encodeVideoSourceFacetInput : VideoSourceFacetInput -> Value
encodeVideoSourceFacetInput input____ =
    Encode.maybeObject
        [ ( "aggregate", Encode.bool |> Encode.optional input____.aggregate ), ( "filter", (Encode.enum Magnes.Api.Enum.VideoSource.toString |> Encode.maybe |> Encode.list) |> Encode.optional input____.filter ) ]
