-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


self :
    SelectionSet decodesTo Magnes.Api.Object.SelfMutation
    -> SelectionSet decodesTo RootMutation
self object____ =
    Object.selectionForCompositeField "self" [] object____ Basics.identity


auth :
    SelectionSet decodesTo Magnes.Api.Object.AuthMutation
    -> SelectionSet decodesTo RootMutation
auth object____ =
    Object.selectionForCompositeField "auth" [] object____ Basics.identity


torrent :
    SelectionSet decodesTo Magnes.Api.Object.TorrentMutation
    -> SelectionSet decodesTo RootMutation
torrent object____ =
    Object.selectionForCompositeField "torrent" [] object____ Basics.identity


queue :
    SelectionSet decodesTo Magnes.Api.Object.QueueMutation
    -> SelectionSet decodesTo RootMutation
queue object____ =
    Object.selectionForCompositeField "queue" [] object____ Basics.identity
