-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object exposing (..)


type APIKey
    = APIKey


type AuthMutation
    = AuthMutation


type AuthObjectAction
    = AuthObjectAction


type AuthQuery
    = AuthQuery


type AuthSubject
    = AuthSubject


type Content
    = Content


type ContentAttribute
    = ContentAttribute


type ContentCollection
    = ContentCollection


type ContentTypeAgg
    = ContentTypeAgg


type CreateAPIKeyResult
    = CreateAPIKeyResult


type Episodes
    = Episodes


type ExternalLink
    = ExternalLink


type GenreAgg
    = GenreAgg


type HealthCheck
    = HealthCheck


type HealthQuery
    = HealthQuery


type Invitation
    = Invitation


type LanguageAgg
    = LanguageAgg


type LanguageInfo
    = LanguageInfo


type ListInvitationsResult
    = ListInvitationsResult


type ListUsersResult
    = ListUsersResult


type LoginResult
    = LoginResult


type MetadataSource
    = MetadataSource


type PasswordEntropyResult
    = PasswordEntropyResult


type Permission
    = Permission


type QueueJob
    = QueueJob


type QueueJobQueueAgg
    = QueueJobQueueAgg


type QueueJobStatusAgg
    = QueueJobStatusAgg


type QueueJobsAggregations
    = QueueJobsAggregations


type QueueJobsQueryResult
    = QueueJobsQueryResult


type QueueMetricsBucket
    = QueueMetricsBucket


type QueueMetricsQueryResult
    = QueueMetricsQueryResult


type QueueMutation
    = QueueMutation


type QueueQuery
    = QueueQuery


type RegisterResult
    = RegisterResult


type ReleaseYearAgg
    = ReleaseYearAgg


type Role
    = Role


type Season
    = Season


type Self
    = Self


type SelfMutation
    = SelfMutation


type SelfQuery
    = SelfQuery


type SuggestedTag
    = SuggestedTag


type Torrent
    = Torrent


type TorrentContent
    = TorrentContent


type TorrentContentAggregations
    = TorrentContentAggregations


type TorrentContentQuery
    = TorrentContentQuery


type TorrentContentSearchResult
    = TorrentContentSearchResult


type TorrentFile
    = TorrentFile


type TorrentFileTypeAgg
    = TorrentFileTypeAgg


type TorrentFilesQueryResult
    = TorrentFilesQueryResult


type TorrentListSourcesResult
    = TorrentListSourcesResult


type TorrentMetricsBucket
    = TorrentMetricsBucket


type TorrentMetricsQueryResult
    = TorrentMetricsQueryResult


type TorrentMutation
    = TorrentMutation


type TorrentQuery
    = TorrentQuery


type TorrentSource
    = TorrentSource


type TorrentSourceAgg
    = TorrentSourceAgg


type TorrentSourceInfo
    = TorrentSourceInfo


type TorrentSuggestTagsResult
    = TorrentSuggestTagsResult


type TorrentTagAgg
    = TorrentTagAgg


type User
    = User


type VideoResolutionAgg
    = VideoResolutionAgg


type VideoSourceAgg
    = VideoSourceAgg


type Worker
    = Worker


type WorkersListAllQueryResult
    = WorkersListAllQueryResult


type WorkersQuery
    = WorkersQuery
