-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object exposing (..)


type Content
    = Content


type ContentAttribute
    = ContentAttribute


type ContentCollection
    = ContentCollection


type ContentTypeAgg
    = ContentTypeAgg


type Episodes
    = Episodes


type ExternalLink
    = ExternalLink


type GenreAgg
    = GenreAgg


type HealthCheck
    = HealthCheck


type HealthQuery
    = HealthQuery


type LanguageAgg
    = LanguageAgg


type LanguageInfo
    = LanguageInfo


type MetadataSource
    = MetadataSource


type QueueJob
    = QueueJob


type QueueJobQueueAgg
    = QueueJobQueueAgg


type QueueJobStatusAgg
    = QueueJobStatusAgg


type QueueJobsAggregations
    = QueueJobsAggregations


type QueueJobsQueryResult
    = QueueJobsQueryResult


type QueueMetricsBucket
    = QueueMetricsBucket


type QueueMetricsQueryResult
    = QueueMetricsQueryResult


type QueueMutation
    = QueueMutation


type QueueQuery
    = QueueQuery


type ReleaseYearAgg
    = ReleaseYearAgg


type Season
    = Season


type SuggestedTag
    = SuggestedTag


type Torrent
    = Torrent


type TorrentContent
    = TorrentContent


type TorrentContentAggregations
    = TorrentContentAggregations


type TorrentContentQuery
    = TorrentContentQuery


type TorrentContentSearchResult
    = TorrentContentSearchResult


type TorrentFile
    = TorrentFile


type TorrentFileTypeAgg
    = TorrentFileTypeAgg


type TorrentFilesQueryResult
    = TorrentFilesQueryResult


type TorrentListSourcesResult
    = TorrentListSourcesResult


type TorrentMetricsBucket
    = TorrentMetricsBucket


type TorrentMetricsQueryResult
    = TorrentMetricsQueryResult


type TorrentMutation
    = TorrentMutation


type TorrentQuery
    = TorrentQuery


type TorrentSource
    = TorrentSource


type TorrentSourceAgg
    = TorrentSourceAgg


type TorrentSourceInfo
    = TorrentSourceInfo


type TorrentSuggestTagsResult
    = TorrentSuggestTagsResult


type TorrentTagAgg
    = TorrentTagAgg


type VideoResolutionAgg
    = VideoResolutionAgg


type VideoSourceAgg
    = VideoSourceAgg


type Worker
    = Worker


type WorkersListAllQueryResult
    = WorkersListAllQueryResult


type WorkersQuery
    = WorkersQuery
