-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Query exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


version : SelectionSet String RootQuery
version =
    Object.selectionForField "String" "version" [] Decode.string


self :
    SelectionSet decodesTo Magnes.Api.Object.SelfQuery
    -> SelectionSet decodesTo RootQuery
self object____ =
    Object.selectionForCompositeField "self" [] object____ Basics.identity


auth :
    SelectionSet decodesTo Magnes.Api.Object.AuthQuery
    -> SelectionSet decodesTo RootQuery
auth object____ =
    Object.selectionForCompositeField "auth" [] object____ Basics.identity


workers :
    SelectionSet decodesTo Magnes.Api.Object.WorkersQuery
    -> SelectionSet decodesTo RootQuery
workers object____ =
    Object.selectionForCompositeField "workers" [] object____ Basics.identity


health :
    SelectionSet decodesTo Magnes.Api.Object.HealthQuery
    -> SelectionSet decodesTo RootQuery
health object____ =
    Object.selectionForCompositeField "health" [] object____ Basics.identity


queue :
    SelectionSet decodesTo Magnes.Api.Object.QueueQuery
    -> SelectionSet decodesTo RootQuery
queue object____ =
    Object.selectionForCompositeField "queue" [] object____ Basics.identity


torrent :
    SelectionSet decodesTo Magnes.Api.Object.TorrentQuery
    -> SelectionSet decodesTo RootQuery
torrent object____ =
    Object.selectionForCompositeField "torrent" [] object____ Basics.identity


torrentContent :
    SelectionSet decodesTo Magnes.Api.Object.TorrentContentQuery
    -> SelectionSet decodesTo RootQuery
torrentContent object____ =
    Object.selectionForCompositeField "torrentContent" [] object____ Basics.identity
