-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Scalar exposing (Codecs, Date(..), DateTime(..), Duration(..), Hash20(..), Id(..), Void(..), Year(..), defaultCodecs, defineCodecs, unwrapCodecs, unwrapEncoder)

import Graphql.Codec exposing (Codec)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode
import Json.Decode as Decode exposing (Decoder)
import Json.Encode as Encode


type Date
    = Date String


type DateTime
    = DateTime String


type Duration
    = Duration String


type Hash20
    = Hash20 String


type Id
    = Id String


type Void
    = Void String


type Year
    = Year String


defineCodecs :
    { codecDate : Codec valueDate
    , codecDateTime : Codec valueDateTime
    , codecDuration : Codec valueDuration
    , codecHash20 : Codec valueHash20
    , codecId : Codec valueId
    , codecVoid : Codec valueVoid
    , codecYear : Codec valueYear
    }
    -> Codecs valueDate valueDateTime valueDuration valueHash20 valueId valueVoid valueYear
defineCodecs definitions =
    Codecs definitions


unwrapCodecs :
    Codecs valueDate valueDateTime valueDuration valueHash20 valueId valueVoid valueYear
    ->
        { codecDate : Codec valueDate
        , codecDateTime : Codec valueDateTime
        , codecDuration : Codec valueDuration
        , codecHash20 : Codec valueHash20
        , codecId : Codec valueId
        , codecVoid : Codec valueVoid
        , codecYear : Codec valueYear
        }
unwrapCodecs (Codecs unwrappedCodecs) =
    unwrappedCodecs


unwrapEncoder :
    (RawCodecs valueDate valueDateTime valueDuration valueHash20 valueId valueVoid valueYear -> Codec getterValue)
    -> Codecs valueDate valueDateTime valueDuration valueHash20 valueId valueVoid valueYear
    -> getterValue
    -> Graphql.Internal.Encode.Value
unwrapEncoder getter (Codecs unwrappedCodecs) =
    (unwrappedCodecs |> getter |> .encoder) >> Graphql.Internal.Encode.fromJson


type Codecs valueDate valueDateTime valueDuration valueHash20 valueId valueVoid valueYear
    = Codecs (RawCodecs valueDate valueDateTime valueDuration valueHash20 valueId valueVoid valueYear)


type alias RawCodecs valueDate valueDateTime valueDuration valueHash20 valueId valueVoid valueYear =
    { codecDate : Codec valueDate
    , codecDateTime : Codec valueDateTime
    , codecDuration : Codec valueDuration
    , codecHash20 : Codec valueHash20
    , codecId : Codec valueId
    , codecVoid : Codec valueVoid
    , codecYear : Codec valueYear
    }


defaultCodecs : RawCodecs Date DateTime Duration Hash20 Id Void Year
defaultCodecs =
    { codecDate =
        { encoder = \(Date raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Date
        }
    , codecDateTime =
        { encoder = \(DateTime raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map DateTime
        }
    , codecDuration =
        { encoder = \(Duration raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Duration
        }
    , codecHash20 =
        { encoder = \(Hash20 raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Hash20
        }
    , codecId =
        { encoder = \(Id raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Id
        }
    , codecVoid =
        { encoder = \(Void raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Void
        }
    , codecYear =
        { encoder = \(Year raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Year
        }
    }
