-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.AuthSubjectType exposing (..)

import Json.Decode as Decode exposing (Decoder)


type AuthSubjectType
    = Role


list : List AuthSubjectType
list =
    [ Role ]


decoder : Decoder AuthSubjectType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "role" ->
                        Decode.succeed Role

                    _ ->
                        Decode.fail ("Invalid AuthSubjectType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : AuthSubjectType -> String
toString enum____ =
    case enum____ of
        Role ->
            "role"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe AuthSubjectType
fromString enumString____ =
    case enumString____ of
        "role" ->
            Just Role

        _ ->
            Nothing
