-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.ContentType exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ContentType
    = Movie
    | Tv_show
    | Music
    | Ebook
    | Comic
    | Audiobook
    | Game
    | Software
    | Xxx


list : List ContentType
list =
    [ Movie, Tv_show, Music, Ebook, Comic, Audiobook, Game, Software, Xxx ]


decoder : Decoder ContentType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "movie" ->
                        Decode.succeed Movie

                    "tv_show" ->
                        Decode.succeed Tv_show

                    "music" ->
                        Decode.succeed Music

                    "ebook" ->
                        Decode.succeed Ebook

                    "comic" ->
                        Decode.succeed Comic

                    "audiobook" ->
                        Decode.succeed Audiobook

                    "game" ->
                        Decode.succeed Game

                    "software" ->
                        Decode.succeed Software

                    "xxx" ->
                        Decode.succeed Xxx

                    _ ->
                        Decode.fail ("Invalid ContentType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : ContentType -> String
toString enum____ =
    case enum____ of
        Movie ->
            "movie"

        Tv_show ->
            "tv_show"

        Music ->
            "music"

        Ebook ->
            "ebook"

        Comic ->
            "comic"

        Audiobook ->
            "audiobook"

        Game ->
            "game"

        Software ->
            "software"

        Xxx ->
            "xxx"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ContentType
fromString enumString____ =
    case enumString____ of
        "movie" ->
            Just Movie

        "tv_show" ->
            Just Tv_show

        "music" ->
            Just Music

        "ebook" ->
            Just Ebook

        "comic" ->
            Just Comic

        "audiobook" ->
            Just Audiobook

        "game" ->
            Just Game

        "software" ->
            Just Software

        "xxx" ->
            Just Xxx

        _ ->
            Nothing
