-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.FileType exposing (..)

import Json.Decode as Decode exposing (Decoder)


type FileType
    = Archive
    | Audio
    | Data
    | Document
    | Image
    | Software
    | Subtitles
    | Video


list : List FileType
list =
    [ Archive, Audio, Data, Document, Image, Software, Subtitles, Video ]


decoder : Decoder FileType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "archive" ->
                        Decode.succeed Archive

                    "audio" ->
                        Decode.succeed Audio

                    "data" ->
                        Decode.succeed Data

                    "document" ->
                        Decode.succeed Document

                    "image" ->
                        Decode.succeed Image

                    "software" ->
                        Decode.succeed Software

                    "subtitles" ->
                        Decode.succeed Subtitles

                    "video" ->
                        Decode.succeed Video

                    _ ->
                        Decode.fail ("Invalid FileType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : FileType -> String
toString enum____ =
    case enum____ of
        Archive ->
            "archive"

        Audio ->
            "audio"

        Data ->
            "data"

        Document ->
            "document"

        Image ->
            "image"

        Software ->
            "software"

        Subtitles ->
            "subtitles"

        Video ->
            "video"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe FileType
fromString enumString____ =
    case enumString____ of
        "archive" ->
            Just Archive

        "audio" ->
            Just Audio

        "data" ->
            Just Data

        "document" ->
            Just Document

        "image" ->
            Just Image

        "software" ->
            Just Software

        "subtitles" ->
            Just Subtitles

        "video" ->
            Just Video

        _ ->
            Nothing
