-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.FilesStatus exposing (..)

import Json.Decode as Decode exposing (Decoder)


type FilesStatus
    = No_info
    | Single
    | Multi
    | Over_threshold


list : List FilesStatus
list =
    [ No_info, Single, Multi, Over_threshold ]


decoder : Decoder FilesStatus
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "no_info" ->
                        Decode.succeed No_info

                    "single" ->
                        Decode.succeed Single

                    "multi" ->
                        Decode.succeed Multi

                    "over_threshold" ->
                        Decode.succeed Over_threshold

                    _ ->
                        Decode.fail ("Invalid FilesStatus type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : FilesStatus -> String
toString enum____ =
    case enum____ of
        No_info ->
            "no_info"

        Single ->
            "single"

        Multi ->
            "multi"

        Over_threshold ->
            "over_threshold"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe FilesStatus
fromString enumString____ =
    case enumString____ of
        "no_info" ->
            Just No_info

        "single" ->
            Just Single

        "multi" ->
            Just Multi

        "over_threshold" ->
            Just Over_threshold

        _ ->
            Nothing
