-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.HealthStatus exposing (..)

import Json.Decode as Decode exposing (Decoder)


type HealthStatus
    = Unknown
    | Inactive
    | Up
    | Down


list : List HealthStatus
list =
    [ Unknown, Inactive, Up, Down ]


decoder : Decoder HealthStatus
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "unknown" ->
                        Decode.succeed Unknown

                    "inactive" ->
                        Decode.succeed Inactive

                    "up" ->
                        Decode.succeed Up

                    "down" ->
                        Decode.succeed Down

                    _ ->
                        Decode.fail ("Invalid HealthStatus type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : HealthStatus -> String
toString enum____ =
    case enum____ of
        Unknown ->
            "unknown"

        Inactive ->
            "inactive"

        Up ->
            "up"

        Down ->
            "down"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe HealthStatus
fromString enumString____ =
    case enumString____ of
        "unknown" ->
            Just Unknown

        "inactive" ->
            Just Inactive

        "up" ->
            Just Up

        "down" ->
            Just Down

        _ ->
            Nothing
