-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.Language exposing (..)

import Json.Decode as Decode exposing (Decoder)


type Language
    = Af
    | Ar
    | Az
    | Be
    | Bg
    | Bs
    | Ca
    | Ce
    | Co
    | Cs
    | Cy
    | Da
    | De
    | El
    | En
    | Es
    | Et
    | Eu
    | Fa
    | Fi
    | Fr
    | He
    | Hi
    | Hr
    | Hu
    | Hy
    | Id
    | Is
    | It
    | Ja
    | Ka
    | Ko
    | Ku
    | Lt
    | Lv
    | Mi
    | Mk
    | Ml
    | Mn
    | Ms
    | Mt
    | Nl
    | No
    | Pl
    | Pt
    | Ro
    | Ru
    | Sa
    | Sk
    | Sl
    | Sm
    | So
    | Sr
    | Sv
    | Ta
    | Th
    | Tr
    | Uk
    | Vi
    | Yi
    | Zh
    | Zu


list : List Language
list =
    [ Af, Ar, Az, Be, Bg, Bs, Ca, Ce, Co, Cs, Cy, Da, De, El, En, Es, Et, Eu, Fa, Fi, Fr, He, Hi, Hr, Hu, Hy, Id, Is, It, Ja, Ka, Ko, Ku, Lt, Lv, Mi, Mk, Ml, Mn, Ms, Mt, Nl, No, Pl, Pt, Ro, Ru, Sa, Sk, Sl, Sm, So, Sr, Sv, Ta, Th, Tr, Uk, Vi, Yi, Zh, Zu ]


decoder : Decoder Language
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "af" ->
                        Decode.succeed Af

                    "ar" ->
                        Decode.succeed Ar

                    "az" ->
                        Decode.succeed Az

                    "be" ->
                        Decode.succeed Be

                    "bg" ->
                        Decode.succeed Bg

                    "bs" ->
                        Decode.succeed Bs

                    "ca" ->
                        Decode.succeed Ca

                    "ce" ->
                        Decode.succeed Ce

                    "co" ->
                        Decode.succeed Co

                    "cs" ->
                        Decode.succeed Cs

                    "cy" ->
                        Decode.succeed Cy

                    "da" ->
                        Decode.succeed Da

                    "de" ->
                        Decode.succeed De

                    "el" ->
                        Decode.succeed El

                    "en" ->
                        Decode.succeed En

                    "es" ->
                        Decode.succeed Es

                    "et" ->
                        Decode.succeed Et

                    "eu" ->
                        Decode.succeed Eu

                    "fa" ->
                        Decode.succeed Fa

                    "fi" ->
                        Decode.succeed Fi

                    "fr" ->
                        Decode.succeed Fr

                    "he" ->
                        Decode.succeed He

                    "hi" ->
                        Decode.succeed Hi

                    "hr" ->
                        Decode.succeed Hr

                    "hu" ->
                        Decode.succeed Hu

                    "hy" ->
                        Decode.succeed Hy

                    "id" ->
                        Decode.succeed Id

                    "is" ->
                        Decode.succeed Is

                    "it" ->
                        Decode.succeed It

                    "ja" ->
                        Decode.succeed Ja

                    "ka" ->
                        Decode.succeed Ka

                    "ko" ->
                        Decode.succeed Ko

                    "ku" ->
                        Decode.succeed Ku

                    "lt" ->
                        Decode.succeed Lt

                    "lv" ->
                        Decode.succeed Lv

                    "mi" ->
                        Decode.succeed Mi

                    "mk" ->
                        Decode.succeed Mk

                    "ml" ->
                        Decode.succeed Ml

                    "mn" ->
                        Decode.succeed Mn

                    "ms" ->
                        Decode.succeed Ms

                    "mt" ->
                        Decode.succeed Mt

                    "nl" ->
                        Decode.succeed Nl

                    "no" ->
                        Decode.succeed No

                    "pl" ->
                        Decode.succeed Pl

                    "pt" ->
                        Decode.succeed Pt

                    "ro" ->
                        Decode.succeed Ro

                    "ru" ->
                        Decode.succeed Ru

                    "sa" ->
                        Decode.succeed Sa

                    "sk" ->
                        Decode.succeed Sk

                    "sl" ->
                        Decode.succeed Sl

                    "sm" ->
                        Decode.succeed Sm

                    "so" ->
                        Decode.succeed So

                    "sr" ->
                        Decode.succeed Sr

                    "sv" ->
                        Decode.succeed Sv

                    "ta" ->
                        Decode.succeed Ta

                    "th" ->
                        Decode.succeed Th

                    "tr" ->
                        Decode.succeed Tr

                    "uk" ->
                        Decode.succeed Uk

                    "vi" ->
                        Decode.succeed Vi

                    "yi" ->
                        Decode.succeed Yi

                    "zh" ->
                        Decode.succeed Zh

                    "zu" ->
                        Decode.succeed Zu

                    _ ->
                        Decode.fail ("Invalid Language type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Language -> String
toString enum____ =
    case enum____ of
        Af ->
            "af"

        Ar ->
            "ar"

        Az ->
            "az"

        Be ->
            "be"

        Bg ->
            "bg"

        Bs ->
            "bs"

        Ca ->
            "ca"

        Ce ->
            "ce"

        Co ->
            "co"

        Cs ->
            "cs"

        Cy ->
            "cy"

        Da ->
            "da"

        De ->
            "de"

        El ->
            "el"

        En ->
            "en"

        Es ->
            "es"

        Et ->
            "et"

        Eu ->
            "eu"

        Fa ->
            "fa"

        Fi ->
            "fi"

        Fr ->
            "fr"

        He ->
            "he"

        Hi ->
            "hi"

        Hr ->
            "hr"

        Hu ->
            "hu"

        Hy ->
            "hy"

        Id ->
            "id"

        Is ->
            "is"

        It ->
            "it"

        Ja ->
            "ja"

        Ka ->
            "ka"

        Ko ->
            "ko"

        Ku ->
            "ku"

        Lt ->
            "lt"

        Lv ->
            "lv"

        Mi ->
            "mi"

        Mk ->
            "mk"

        Ml ->
            "ml"

        Mn ->
            "mn"

        Ms ->
            "ms"

        Mt ->
            "mt"

        Nl ->
            "nl"

        No ->
            "no"

        Pl ->
            "pl"

        Pt ->
            "pt"

        Ro ->
            "ro"

        Ru ->
            "ru"

        Sa ->
            "sa"

        Sk ->
            "sk"

        Sl ->
            "sl"

        Sm ->
            "sm"

        So ->
            "so"

        Sr ->
            "sr"

        Sv ->
            "sv"

        Ta ->
            "ta"

        Th ->
            "th"

        Tr ->
            "tr"

        Uk ->
            "uk"

        Vi ->
            "vi"

        Yi ->
            "yi"

        Zh ->
            "zh"

        Zu ->
            "zu"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Language
fromString enumString____ =
    case enumString____ of
        "af" ->
            Just Af

        "ar" ->
            Just Ar

        "az" ->
            Just Az

        "be" ->
            Just Be

        "bg" ->
            Just Bg

        "bs" ->
            Just Bs

        "ca" ->
            Just Ca

        "ce" ->
            Just Ce

        "co" ->
            Just Co

        "cs" ->
            Just Cs

        "cy" ->
            Just Cy

        "da" ->
            Just Da

        "de" ->
            Just De

        "el" ->
            Just El

        "en" ->
            Just En

        "es" ->
            Just Es

        "et" ->
            Just Et

        "eu" ->
            Just Eu

        "fa" ->
            Just Fa

        "fi" ->
            Just Fi

        "fr" ->
            Just Fr

        "he" ->
            Just He

        "hi" ->
            Just Hi

        "hr" ->
            Just Hr

        "hu" ->
            Just Hu

        "hy" ->
            Just Hy

        "id" ->
            Just Id

        "is" ->
            Just Is

        "it" ->
            Just It

        "ja" ->
            Just Ja

        "ka" ->
            Just Ka

        "ko" ->
            Just Ko

        "ku" ->
            Just Ku

        "lt" ->
            Just Lt

        "lv" ->
            Just Lv

        "mi" ->
            Just Mi

        "mk" ->
            Just Mk

        "ml" ->
            Just Ml

        "mn" ->
            Just Mn

        "ms" ->
            Just Ms

        "mt" ->
            Just Mt

        "nl" ->
            Just Nl

        "no" ->
            Just No

        "pl" ->
            Just Pl

        "pt" ->
            Just Pt

        "ro" ->
            Just Ro

        "ru" ->
            Just Ru

        "sa" ->
            Just Sa

        "sk" ->
            Just Sk

        "sl" ->
            Just Sl

        "sm" ->
            Just Sm

        "so" ->
            Just So

        "sr" ->
            Just Sr

        "sv" ->
            Just Sv

        "ta" ->
            Just Ta

        "th" ->
            Just Th

        "tr" ->
            Just Tr

        "uk" ->
            Just Uk

        "vi" ->
            Just Vi

        "yi" ->
            Just Yi

        "zh" ->
            Just Zh

        "zu" ->
            Just Zu

        _ ->
            Nothing
