-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.MetricsBucketDuration exposing (..)

import Json.Decode as Decode exposing (Decoder)


type MetricsBucketDuration
    = Minute
    | Hour
    | Day


list : List MetricsBucketDuration
list =
    [ Minute, Hour, Day ]


decoder : Decoder MetricsBucketDuration
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "minute" ->
                        Decode.succeed Minute

                    "hour" ->
                        Decode.succeed Hour

                    "day" ->
                        Decode.succeed Day

                    _ ->
                        Decode.fail ("Invalid MetricsBucketDuration type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : MetricsBucketDuration -> String
toString enum____ =
    case enum____ of
        Minute ->
            "minute"

        Hour ->
            "hour"

        Day ->
            "day"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe MetricsBucketDuration
fromString enumString____ =
    case enumString____ of
        "minute" ->
            Just Minute

        "hour" ->
            Just Hour

        "day" ->
            Just Day

        _ ->
            Nothing
