-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.QueueJobStatus exposing (..)

import Json.Decode as Decode exposing (Decoder)


type QueueJobStatus
    = Pending
    | Retry
    | Failed
    | Processed


list : List QueueJobStatus
list =
    [ Pending, Retry, Failed, Processed ]


decoder : Decoder QueueJobStatus
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "pending" ->
                        Decode.succeed Pending

                    "retry" ->
                        Decode.succeed Retry

                    "failed" ->
                        Decode.succeed Failed

                    "processed" ->
                        Decode.succeed Processed

                    _ ->
                        Decode.fail ("Invalid QueueJobStatus type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : QueueJobStatus -> String
toString enum____ =
    case enum____ of
        Pending ->
            "pending"

        Retry ->
            "retry"

        Failed ->
            "failed"

        Processed ->
            "processed"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe QueueJobStatus
fromString enumString____ =
    case enumString____ of
        "pending" ->
            Just Pending

        "retry" ->
            Just Retry

        "failed" ->
            Just Failed

        "processed" ->
            Just Processed

        _ ->
            Nothing
