-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.QueueJobsOrderByField exposing (..)

import Json.Decode as Decode exposing (Decoder)


type QueueJobsOrderByField
    = Created_at
    | Ran_at
    | Priority


list : List QueueJobsOrderByField
list =
    [ Created_at, Ran_at, Priority ]


decoder : Decoder QueueJobsOrderByField
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "created_at" ->
                        Decode.succeed Created_at

                    "ran_at" ->
                        Decode.succeed Ran_at

                    "priority" ->
                        Decode.succeed Priority

                    _ ->
                        Decode.fail ("Invalid QueueJobsOrderByField type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : QueueJobsOrderByField -> String
toString enum____ =
    case enum____ of
        Created_at ->
            "created_at"

        Ran_at ->
            "ran_at"

        Priority ->
            "priority"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe QueueJobsOrderByField
fromString enumString____ =
    case enumString____ of
        "created_at" ->
            Just Created_at

        "ran_at" ->
            Just Ran_at

        "priority" ->
            Just Priority

        _ ->
            Nothing
