-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.TorrentFilesOrderByField exposing (..)

import Json.Decode as Decode exposing (Decoder)


type TorrentFilesOrderByField
    = Index
    | Path
    | Extension
    | Size


list : List TorrentFilesOrderByField
list =
    [ Index, Path, Extension, Size ]


decoder : Decoder TorrentFilesOrderByField
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "index" ->
                        Decode.succeed Index

                    "path" ->
                        Decode.succeed Path

                    "extension" ->
                        Decode.succeed Extension

                    "size" ->
                        Decode.succeed Size

                    _ ->
                        Decode.fail ("Invalid TorrentFilesOrderByField type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : TorrentFilesOrderByField -> String
toString enum____ =
    case enum____ of
        Index ->
            "index"

        Path ->
            "path"

        Extension ->
            "extension"

        Size ->
            "size"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe TorrentFilesOrderByField
fromString enumString____ =
    case enumString____ of
        "index" ->
            Just Index

        "path" ->
            Just Path

        "extension" ->
            Just Extension

        "size" ->
            Just Size

        _ ->
            Nothing
