-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.TorrentContentOrderByField exposing (..)

import Json.Decode as Decode exposing (Decoder)


type TorrentContentOrderByField
    = Relevance
    | Published_at
    | Updated_at
    | Size
    | Files_count
    | Seeders
    | Leechers
    | Name
    | Info_hash


list : List TorrentContentOrderByField
list =
    [ Relevance, Published_at, Updated_at, Size, Files_count, Seeders, Leechers, Name, Info_hash ]


decoder : Decoder TorrentContentOrderByField
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "relevance" ->
                        Decode.succeed Relevance

                    "published_at" ->
                        Decode.succeed Published_at

                    "updated_at" ->
                        Decode.succeed Updated_at

                    "size" ->
                        Decode.succeed Size

                    "files_count" ->
                        Decode.succeed Files_count

                    "seeders" ->
                        Decode.succeed Seeders

                    "leechers" ->
                        Decode.succeed Leechers

                    "name" ->
                        Decode.succeed Name

                    "info_hash" ->
                        Decode.succeed Info_hash

                    _ ->
                        Decode.fail ("Invalid TorrentContentOrderByField type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : TorrentContentOrderByField -> String
toString enum____ =
    case enum____ of
        Relevance ->
            "relevance"

        Published_at ->
            "published_at"

        Updated_at ->
            "updated_at"

        Size ->
            "size"

        Files_count ->
            "files_count"

        Seeders ->
            "seeders"

        Leechers ->
            "leechers"

        Name ->
            "name"

        Info_hash ->
            "info_hash"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe TorrentContentOrderByField
fromString enumString____ =
    case enumString____ of
        "relevance" ->
            Just Relevance

        "published_at" ->
            Just Published_at

        "updated_at" ->
            Just Updated_at

        "size" ->
            Just Size

        "files_count" ->
            Just Files_count

        "seeders" ->
            Just Seeders

        "leechers" ->
            Just Leechers

        "name" ->
            Just Name

        "info_hash" ->
            Just Info_hash

        _ ->
            Nothing
