-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.VideoCodec exposing (..)

import Json.Decode as Decode exposing (Decoder)


type VideoCodec
    = Av1
    | H264
    | X264
    | X265
    | XviD
    | DivX
    | Mpeg2
    | Mpeg4


list : List VideoCodec
list =
    [ Av1, H264, X264, X265, XviD, DivX, Mpeg2, Mpeg4 ]


decoder : Decoder VideoCodec
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "AV1" ->
                        Decode.succeed Av1

                    "H264" ->
                        Decode.succeed H264

                    "x264" ->
                        Decode.succeed X264

                    "x265" ->
                        Decode.succeed X265

                    "XviD" ->
                        Decode.succeed XviD

                    "DivX" ->
                        Decode.succeed DivX

                    "MPEG2" ->
                        Decode.succeed Mpeg2

                    "MPEG4" ->
                        Decode.succeed Mpeg4

                    _ ->
                        Decode.fail ("Invalid VideoCodec type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : VideoCodec -> String
toString enum____ =
    case enum____ of
        Av1 ->
            "AV1"

        H264 ->
            "H264"

        X264 ->
            "x264"

        X265 ->
            "x265"

        XviD ->
            "XviD"

        DivX ->
            "DivX"

        Mpeg2 ->
            "MPEG2"

        Mpeg4 ->
            "MPEG4"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe VideoCodec
fromString enumString____ =
    case enumString____ of
        "AV1" ->
            Just Av1

        "H264" ->
            Just H264

        "x264" ->
            Just X264

        "x265" ->
            Just X265

        "XviD" ->
            Just XviD

        "DivX" ->
            Just DivX

        "MPEG2" ->
            Just Mpeg2

        "MPEG4" ->
            Just Mpeg4

        _ ->
            Nothing
