-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.VideoSource exposing (..)

import Json.Decode as Decode exposing (Decoder)


type VideoSource
    = Cam
    | Telesync
    | Telecine
    | Workprint
    | Dvd
    | Tv
    | Webdl
    | WEBRip
    | BluRay


list : List VideoSource
list =
    [ Cam, Telesync, Telecine, Workprint, Dvd, Tv, Webdl, WEBRip, BluRay ]


decoder : Decoder VideoSource
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "CAM" ->
                        Decode.succeed Cam

                    "TELESYNC" ->
                        Decode.succeed Telesync

                    "TELECINE" ->
                        Decode.succeed Telecine

                    "WORKPRINT" ->
                        Decode.succeed Workprint

                    "DVD" ->
                        Decode.succeed Dvd

                    "TV" ->
                        Decode.succeed Tv

                    "WEBDL" ->
                        Decode.succeed Webdl

                    "WEBRip" ->
                        Decode.succeed WEBRip

                    "BluRay" ->
                        Decode.succeed BluRay

                    _ ->
                        Decode.fail ("Invalid VideoSource type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : VideoSource -> String
toString enum____ =
    case enum____ of
        Cam ->
            "CAM"

        Telesync ->
            "TELESYNC"

        Telecine ->
            "TELECINE"

        Workprint ->
            "WORKPRINT"

        Dvd ->
            "DVD"

        Tv ->
            "TV"

        Webdl ->
            "WEBDL"

        WEBRip ->
            "WEBRip"

        BluRay ->
            "BluRay"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe VideoSource
fromString enumString____ =
    case enumString____ of
        "CAM" ->
            Just Cam

        "TELESYNC" ->
            Just Telesync

        "TELECINE" ->
            Just Telecine

        "WORKPRINT" ->
            Just Workprint

        "DVD" ->
            Just Dvd

        "TV" ->
            Just Tv

        "WEBDL" ->
            Just Webdl

        "WEBRip" ->
            Just WEBRip

        "BluRay" ->
            Just BluRay

        _ ->
            Nothing
