-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.Video3D exposing (..)

import Json.Decode as Decode exposing (Decoder)


type Video3D
    = V3d
    | V3dsbs
    | V3dou


list : List Video3D
list =
    [ V3d, V3dsbs, V3dou ]


decoder : Decoder Video3D
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "V3D" ->
                        Decode.succeed V3d

                    "V3DSBS" ->
                        Decode.succeed V3dsbs

                    "V3DOU" ->
                        Decode.succeed V3dou

                    _ ->
                        Decode.fail ("Invalid Video3D type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Video3D -> String
toString enum____ =
    case enum____ of
        V3d ->
            "V3D"

        V3dsbs ->
            "V3DSBS"

        V3dou ->
            "V3DOU"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Video3D
fromString enumString____ =
    case enumString____ of
        "V3D" ->
            Just V3d

        "V3DSBS" ->
            Just V3dsbs

        "V3DOU" ->
            Just V3dou

        _ ->
            Nothing
