-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.VideoModifier exposing (..)

import Json.Decode as Decode exposing (Decoder)


type VideoModifier
    = Regional
    | Screener
    | Rawhd
    | Brdisk
    | Remux


list : List VideoModifier
list =
    [ Regional, Screener, Rawhd, Brdisk, Remux ]


decoder : Decoder VideoModifier
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "REGIONAL" ->
                        Decode.succeed Regional

                    "SCREENER" ->
                        Decode.succeed Screener

                    "RAWHD" ->
                        Decode.succeed Rawhd

                    "BRDISK" ->
                        Decode.succeed Brdisk

                    "REMUX" ->
                        Decode.succeed Remux

                    _ ->
                        Decode.fail ("Invalid VideoModifier type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : VideoModifier -> String
toString enum____ =
    case enum____ of
        Regional ->
            "REGIONAL"

        Screener ->
            "SCREENER"

        Rawhd ->
            "RAWHD"

        Brdisk ->
            "BRDISK"

        Remux ->
            "REMUX"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe VideoModifier
fromString enumString____ =
    case enumString____ of
        "REGIONAL" ->
            Just Regional

        "SCREENER" ->
            Just Screener

        "RAWHD" ->
            Just Rawhd

        "BRDISK" ->
            Just Brdisk

        "REMUX" ->
            Just Remux

        _ ->
            Nothing
