-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Enum.VideoResolution exposing (..)

import Json.Decode as Decode exposing (Decoder)


type VideoResolution
    = V360p
    | V480p
    | V540p
    | V576p
    | V720p
    | V1080p
    | V1440p
    | V2160p
    | V4320p


list : List VideoResolution
list =
    [ V360p, V480p, V540p, V576p, V720p, V1080p, V1440p, V2160p, V4320p ]


decoder : Decoder VideoResolution
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "V360p" ->
                        Decode.succeed V360p

                    "V480p" ->
                        Decode.succeed V480p

                    "V540p" ->
                        Decode.succeed V540p

                    "V576p" ->
                        Decode.succeed V576p

                    "V720p" ->
                        Decode.succeed V720p

                    "V1080p" ->
                        Decode.succeed V1080p

                    "V1440p" ->
                        Decode.succeed V1440p

                    "V2160p" ->
                        Decode.succeed V2160p

                    "V4320p" ->
                        Decode.succeed V4320p

                    _ ->
                        Decode.fail ("Invalid VideoResolution type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : VideoResolution -> String
toString enum____ =
    case enum____ of
        V360p ->
            "V360p"

        V480p ->
            "V480p"

        V540p ->
            "V540p"

        V576p ->
            "V576p"

        V720p ->
            "V720p"

        V1080p ->
            "V1080p"

        V1440p ->
            "V1440p"

        V2160p ->
            "V2160p"

        V4320p ->
            "V4320p"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe VideoResolution
fromString enumString____ =
    case enumString____ of
        "V360p" ->
            Just V360p

        "V480p" ->
            Just V480p

        "V540p" ->
            Just V540p

        "V576p" ->
            Just V576p

        "V720p" ->
            Just V720p

        "V1080p" ->
            Just V1080p

        "V1440p" ->
            Just V1440p

        "V2160p" ->
            Just V2160p

        "V4320p" ->
            Just V4320p

        _ ->
            Nothing
