-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.APIKey exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


id : SelectionSet Int Magnes.Api.Object.APIKey
id =
    Object.selectionForField "Int" "id" [] Decode.int


name : SelectionSet String Magnes.Api.Object.APIKey
name =
    Object.selectionForField "String" "name" [] Decode.string


userId : SelectionSet Int Magnes.Api.Object.APIKey
userId =
    Object.selectionForField "Int" "userId" [] Decode.int


user :
    SelectionSet decodesTo Magnes.Api.Object.User
    -> SelectionSet decodesTo Magnes.Api.Object.APIKey
user object____ =
    Object.selectionForCompositeField "user" [] object____ Basics.identity


{-| This key's selected object actions: the ones named when it was created. A
property of the key, so it does not change when the owning user's role does.
What the key may exercise right now is `Self.permissions`.
-}
permissions :
    SelectionSet decodesTo Magnes.Api.Object.AuthObjectAction
    -> SelectionSet (List decodesTo) Magnes.Api.Object.APIKey
permissions object____ =
    Object.selectionForCompositeField "permissions" [] object____ (Basics.identity >> Decode.list)


expiresAt : SelectionSet (Maybe Magnes.Api.ScalarCodecs.DateTime) Magnes.Api.Object.APIKey
expiresAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "expiresAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


createdAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.APIKey
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
