-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.AuthSubject exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.AuthSubjectType
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


type_ : SelectionSet Magnes.Api.Enum.AuthSubjectType.AuthSubjectType Magnes.Api.Object.AuthSubject
type_ =
    Object.selectionForField "Enum.AuthSubjectType.AuthSubjectType" "type" [] Magnes.Api.Enum.AuthSubjectType.decoder


name : SelectionSet String Magnes.Api.Object.AuthSubject
name =
    Object.selectionForField "String" "name" [] Decode.string
