-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.AuthQuery exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


type alias ListUsersOptionalArguments =
    { input : OptionalArgument Magnes.Api.InputObject.ListUsersInput }


listUsers :
    (ListUsersOptionalArguments -> ListUsersOptionalArguments)
    -> SelectionSet decodesTo Magnes.Api.Object.ListUsersResult
    -> SelectionSet decodesTo Magnes.Api.Object.AuthQuery
listUsers fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { input = Absent }

        optionalArgs____ =
            [ Argument.optional "input" filledInOptionals____.input Magnes.Api.InputObject.encodeListUsersInput ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "listUsers" optionalArgs____ object____ Basics.identity


listRoles :
    SelectionSet decodesTo Magnes.Api.Object.Role
    -> SelectionSet (List decodesTo) Magnes.Api.Object.AuthQuery
listRoles object____ =
    Object.selectionForCompositeField "listRoles" [] object____ (Basics.identity >> Decode.list)


listObjectActions :
    SelectionSet decodesTo Magnes.Api.Object.AuthObjectAction
    -> SelectionSet (List decodesTo) Magnes.Api.Object.AuthQuery
listObjectActions object____ =
    Object.selectionForCompositeField "listObjectActions" [] object____ (Basics.identity >> Decode.list)


type alias ListInvitationsOptionalArguments =
    { input : OptionalArgument Magnes.Api.InputObject.ListInvitationsInput }


listInvitations :
    (ListInvitationsOptionalArguments -> ListInvitationsOptionalArguments)
    -> SelectionSet decodesTo Magnes.Api.Object.ListInvitationsResult
    -> SelectionSet decodesTo Magnes.Api.Object.AuthQuery
listInvitations fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { input = Absent }

        optionalArgs____ =
            [ Argument.optional "input" filledInOptionals____.input Magnes.Api.InputObject.encodeListInvitationsInput ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "listInvitations" optionalArgs____ object____ Basics.identity
