-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.AuthMutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


type alias SetUserRoleRequiredArguments =
    { userId : Int
    , roleName : String
    }


setUserRole :
    SetUserRoleRequiredArguments
    -> SelectionSet decodesTo Magnes.Api.Object.User
    -> SelectionSet decodesTo Magnes.Api.Object.AuthMutation
setUserRole requiredArgs____ object____ =
    Object.selectionForCompositeField "setUserRole" [ Argument.required "userId" requiredArgs____.userId Encode.int, Argument.required "roleName" requiredArgs____.roleName Encode.string ] object____ Basics.identity


type alias SetUserEnabledRequiredArguments =
    { userId : Int
    , enabled : Bool
    }


setUserEnabled :
    SetUserEnabledRequiredArguments
    -> SelectionSet decodesTo Magnes.Api.Object.User
    -> SelectionSet decodesTo Magnes.Api.Object.AuthMutation
setUserEnabled requiredArgs____ object____ =
    Object.selectionForCompositeField "setUserEnabled" [ Argument.required "userId" requiredArgs____.userId Encode.int, Argument.required "enabled" requiredArgs____.enabled Encode.bool ] object____ Basics.identity


type alias DeleteUserRequiredArguments =
    { userId : Int }


deleteUser :
    DeleteUserRequiredArguments
    -> SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.AuthMutation
deleteUser requiredArgs____ =
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "deleteUser" [ Argument.required "userId" requiredArgs____.userId Encode.int ] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)


type alias PutRoleRequiredArguments =
    { role : String
    , objectActions : List Magnes.Api.InputObject.AuthObjectActionInput
    }


putRole :
    PutRoleRequiredArguments
    -> SelectionSet decodesTo Magnes.Api.Object.Role
    -> SelectionSet decodesTo Magnes.Api.Object.AuthMutation
putRole requiredArgs____ object____ =
    Object.selectionForCompositeField "putRole" [ Argument.required "role" requiredArgs____.role Encode.string, Argument.required "objectActions" requiredArgs____.objectActions (Magnes.Api.InputObject.encodeAuthObjectActionInput |> Encode.list) ] object____ Basics.identity


type alias DeleteRoleRequiredArguments =
    { role : String }


deleteRole :
    DeleteRoleRequiredArguments
    -> SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.AuthMutation
deleteRole requiredArgs____ =
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "deleteRole" [ Argument.required "role" requiredArgs____.role Encode.string ] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)


type alias InviteRequiredArguments =
    { input : Magnes.Api.InputObject.InviteInput }


invite :
    InviteRequiredArguments
    -> SelectionSet decodesTo Magnes.Api.Object.Invitation
    -> SelectionSet decodesTo Magnes.Api.Object.AuthMutation
invite requiredArgs____ object____ =
    Object.selectionForCompositeField "invite" [ Argument.required "input" requiredArgs____.input Magnes.Api.InputObject.encodeInviteInput ] object____ Basics.identity


type alias DeleteInvitationRequiredArguments =
    { code : String }


deleteInvitation :
    DeleteInvitationRequiredArguments
    -> SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.AuthMutation
deleteInvitation requiredArgs____ =
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "deleteInvitation" [ Argument.required "code" requiredArgs____.code Encode.string ] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)
