-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.AuthObjectAction exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


namespace : SelectionSet String Magnes.Api.Object.AuthObjectAction
namespace =
    Object.selectionForField "String" "namespace" [] Decode.string


object : SelectionSet String Magnes.Api.Object.AuthObjectAction
object =
    Object.selectionForField "String" "object" [] Decode.string


action : SelectionSet String Magnes.Api.Object.AuthObjectAction
action =
    Object.selectionForField "String" "action" [] Decode.string
