-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.Content exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.ContentType
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


type_ : SelectionSet Magnes.Api.Enum.ContentType.ContentType Magnes.Api.Object.Content
type_ =
    Object.selectionForField "Enum.ContentType.ContentType" "type" [] Magnes.Api.Enum.ContentType.decoder


source : SelectionSet String Magnes.Api.Object.Content
source =
    Object.selectionForField "String" "source" [] Decode.string


id : SelectionSet String Magnes.Api.Object.Content
id =
    Object.selectionForField "String" "id" [] Decode.string


title : SelectionSet String Magnes.Api.Object.Content
title =
    Object.selectionForField "String" "title" [] Decode.string


releaseDate : SelectionSet (Maybe Magnes.Api.ScalarCodecs.Date) Magnes.Api.Object.Content
releaseDate =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "releaseDate" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


releaseYear : SelectionSet (Maybe Magnes.Api.ScalarCodecs.Year) Magnes.Api.Object.Content
releaseYear =
    Object.selectionForField "(Maybe ScalarCodecs.Year)" "releaseYear" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecYear |> .decoder |> Decode.nullable)


adult : SelectionSet (Maybe Bool) Magnes.Api.Object.Content
adult =
    Object.selectionForField "(Maybe Bool)" "adult" [] (Decode.bool |> Decode.nullable)


originalLanguage :
    SelectionSet decodesTo Magnes.Api.Object.LanguageInfo
    -> SelectionSet (Maybe decodesTo) Magnes.Api.Object.Content
originalLanguage object____ =
    Object.selectionForCompositeField "originalLanguage" [] object____ (Basics.identity >> Decode.nullable)


originalTitle : SelectionSet (Maybe String) Magnes.Api.Object.Content
originalTitle =
    Object.selectionForField "(Maybe String)" "originalTitle" [] (Decode.string |> Decode.nullable)


overview : SelectionSet (Maybe String) Magnes.Api.Object.Content
overview =
    Object.selectionForField "(Maybe String)" "overview" [] (Decode.string |> Decode.nullable)


runtime : SelectionSet (Maybe Int) Magnes.Api.Object.Content
runtime =
    Object.selectionForField "(Maybe Int)" "runtime" [] (Decode.int |> Decode.nullable)


popularity : SelectionSet (Maybe Float) Magnes.Api.Object.Content
popularity =
    Object.selectionForField "(Maybe Float)" "popularity" [] (Decode.float |> Decode.nullable)


voteAverage : SelectionSet (Maybe Float) Magnes.Api.Object.Content
voteAverage =
    Object.selectionForField "(Maybe Float)" "voteAverage" [] (Decode.float |> Decode.nullable)


voteCount : SelectionSet (Maybe Int) Magnes.Api.Object.Content
voteCount =
    Object.selectionForField "(Maybe Int)" "voteCount" [] (Decode.int |> Decode.nullable)


attributes :
    SelectionSet decodesTo Magnes.Api.Object.ContentAttribute
    -> SelectionSet (List decodesTo) Magnes.Api.Object.Content
attributes object____ =
    Object.selectionForCompositeField "attributes" [] object____ (Basics.identity >> Decode.list)


collections :
    SelectionSet decodesTo Magnes.Api.Object.ContentCollection
    -> SelectionSet (List decodesTo) Magnes.Api.Object.Content
collections object____ =
    Object.selectionForCompositeField "collections" [] object____ (Basics.identity >> Decode.list)


metadataSource :
    SelectionSet decodesTo Magnes.Api.Object.MetadataSource
    -> SelectionSet decodesTo Magnes.Api.Object.Content
metadataSource object____ =
    Object.selectionForCompositeField "metadataSource" [] object____ Basics.identity


externalLinks :
    SelectionSet decodesTo Magnes.Api.Object.ExternalLink
    -> SelectionSet (List decodesTo) Magnes.Api.Object.Content
externalLinks object____ =
    Object.selectionForCompositeField "externalLinks" [] object____ (Basics.identity >> Decode.list)


createdAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.Content
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


updatedAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.Content
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
