-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.ContentCollection exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


type_ : SelectionSet String Magnes.Api.Object.ContentCollection
type_ =
    Object.selectionForField "String" "type" [] Decode.string


source : SelectionSet String Magnes.Api.Object.ContentCollection
source =
    Object.selectionForField "String" "source" [] Decode.string


id : SelectionSet String Magnes.Api.Object.ContentCollection
id =
    Object.selectionForField "String" "id" [] Decode.string


name : SelectionSet String Magnes.Api.Object.ContentCollection
name =
    Object.selectionForField "String" "name" [] Decode.string


metadataSource :
    SelectionSet decodesTo Magnes.Api.Object.MetadataSource
    -> SelectionSet decodesTo Magnes.Api.Object.ContentCollection
metadataSource object____ =
    Object.selectionForCompositeField "metadataSource" [] object____ Basics.identity


createdAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.ContentCollection
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


updatedAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.ContentCollection
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
