-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.CreateAPIKeyResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


id : SelectionSet Int Magnes.Api.Object.CreateAPIKeyResult
id =
    Object.selectionForField "Int" "id" [] Decode.int


apiKey : SelectionSet String Magnes.Api.Object.CreateAPIKeyResult
apiKey =
    Object.selectionForField "String" "apiKey" [] Decode.string


name : SelectionSet String Magnes.Api.Object.CreateAPIKeyResult
name =
    Object.selectionForField "String" "name" [] Decode.string


expiresAt : SelectionSet (Maybe Magnes.Api.ScalarCodecs.DateTime) Magnes.Api.Object.CreateAPIKeyResult
expiresAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "expiresAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)
