-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.Episodes exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


label : SelectionSet String Magnes.Api.Object.Episodes
label =
    Object.selectionForField "String" "label" [] Decode.string


seasons :
    SelectionSet decodesTo Magnes.Api.Object.Season
    -> SelectionSet (List decodesTo) Magnes.Api.Object.Episodes
seasons object____ =
    Object.selectionForCompositeField "seasons" [] object____ (Basics.identity >> Decode.list)
