-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.ExternalLink exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


metadataSource :
    SelectionSet decodesTo Magnes.Api.Object.MetadataSource
    -> SelectionSet decodesTo Magnes.Api.Object.ExternalLink
metadataSource object____ =
    Object.selectionForCompositeField "metadataSource" [] object____ Basics.identity


url : SelectionSet String Magnes.Api.Object.ExternalLink
url =
    Object.selectionForField "String" "url" [] Decode.string
