-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.HealthCheck exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.HealthStatus
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


key : SelectionSet String Magnes.Api.Object.HealthCheck
key =
    Object.selectionForField "String" "key" [] Decode.string


status : SelectionSet Magnes.Api.Enum.HealthStatus.HealthStatus Magnes.Api.Object.HealthCheck
status =
    Object.selectionForField "Enum.HealthStatus.HealthStatus" "status" [] Magnes.Api.Enum.HealthStatus.decoder


timestamp : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.HealthCheck
timestamp =
    Object.selectionForField "ScalarCodecs.DateTime" "timestamp" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


error : SelectionSet (Maybe String) Magnes.Api.Object.HealthCheck
error =
    Object.selectionForField "(Maybe String)" "error" [] (Decode.string |> Decode.nullable)
