-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.HealthQuery exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.HealthStatus
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


status : SelectionSet Magnes.Api.Enum.HealthStatus.HealthStatus Magnes.Api.Object.HealthQuery
status =
    Object.selectionForField "Enum.HealthStatus.HealthStatus" "status" [] Magnes.Api.Enum.HealthStatus.decoder


checks :
    SelectionSet decodesTo Magnes.Api.Object.HealthCheck
    -> SelectionSet (List decodesTo) Magnes.Api.Object.HealthQuery
checks object____ =
    Object.selectionForCompositeField "checks" [] object____ (Basics.identity >> Decode.list)
