-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.Invitation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


code : SelectionSet String Magnes.Api.Object.Invitation
code =
    Object.selectionForField "String" "code" [] Decode.string


role : SelectionSet String Magnes.Api.Object.Invitation
role =
    Object.selectionForField "String" "role" [] Decode.string


email : SelectionSet (Maybe String) Magnes.Api.Object.Invitation
email =
    Object.selectionForField "(Maybe String)" "email" [] (Decode.string |> Decode.nullable)


createdBy :
    SelectionSet decodesTo Magnes.Api.Object.User
    -> SelectionSet (Maybe decodesTo) Magnes.Api.Object.Invitation
createdBy object____ =
    Object.selectionForCompositeField "createdBy" [] object____ (Basics.identity >> Decode.nullable)


claimedBy :
    SelectionSet decodesTo Magnes.Api.Object.User
    -> SelectionSet (Maybe decodesTo) Magnes.Api.Object.Invitation
claimedBy object____ =
    Object.selectionForCompositeField "claimedBy" [] object____ (Basics.identity >> Decode.nullable)


expiresAt : SelectionSet (Maybe Magnes.Api.ScalarCodecs.DateTime) Magnes.Api.Object.Invitation
expiresAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "expiresAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


createdAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.Invitation
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
