-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.LanguageAgg exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.Language
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


value : SelectionSet Magnes.Api.Enum.Language.Language Magnes.Api.Object.LanguageAgg
value =
    Object.selectionForField "Enum.Language.Language" "value" [] Magnes.Api.Enum.Language.decoder


label : SelectionSet String Magnes.Api.Object.LanguageAgg
label =
    Object.selectionForField "String" "label" [] Decode.string


count : SelectionSet Int Magnes.Api.Object.LanguageAgg
count =
    Object.selectionForField "Int" "count" [] Decode.int


isEstimate : SelectionSet Bool Magnes.Api.Object.LanguageAgg
isEstimate =
    Object.selectionForField "Bool" "isEstimate" [] Decode.bool
