-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.ListInvitationsResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


invitations :
    SelectionSet decodesTo Magnes.Api.Object.Invitation
    -> SelectionSet (List decodesTo) Magnes.Api.Object.ListInvitationsResult
invitations object____ =
    Object.selectionForCompositeField "invitations" [] object____ (Basics.identity >> Decode.list)


totalCount : SelectionSet Int Magnes.Api.Object.ListInvitationsResult
totalCount =
    Object.selectionForField "Int" "totalCount" [] Decode.int
