-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.PasswordEntropyResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


entropy : SelectionSet Float Magnes.Api.Object.PasswordEntropyResult
entropy =
    Object.selectionForField "Float" "entropy" [] Decode.float


minEntropy : SelectionSet Float Magnes.Api.Object.PasswordEntropyResult
minEntropy =
    Object.selectionForField "Float" "minEntropy" [] Decode.float


valid : SelectionSet Bool Magnes.Api.Object.PasswordEntropyResult
valid =
    Object.selectionForField "Bool" "valid" [] Decode.bool
