-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.Permission exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


subject :
    SelectionSet decodesTo Magnes.Api.Object.AuthSubject
    -> SelectionSet decodesTo Magnes.Api.Object.Permission
subject object____ =
    Object.selectionForCompositeField "subject" [] object____ Basics.identity


objectAction :
    SelectionSet decodesTo Magnes.Api.Object.AuthObjectAction
    -> SelectionSet decodesTo Magnes.Api.Object.Permission
objectAction object____ =
    Object.selectionForCompositeField "objectAction" [] object____ Basics.identity


core : SelectionSet Bool Magnes.Api.Object.Permission
core =
    Object.selectionForField "Bool" "core" [] Decode.bool
