-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.QueueJobsAggregations exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


queue :
    SelectionSet decodesTo Magnes.Api.Object.QueueJobQueueAgg
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.QueueJobsAggregations
queue object____ =
    Object.selectionForCompositeField "queue" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


status :
    SelectionSet decodesTo Magnes.Api.Object.QueueJobStatusAgg
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.QueueJobsAggregations
status object____ =
    Object.selectionForCompositeField "status" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)
