-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.QueueMetricsBucket exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.QueueJobStatus
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


queue : SelectionSet String Magnes.Api.Object.QueueMetricsBucket
queue =
    Object.selectionForField "String" "queue" [] Decode.string


status : SelectionSet Magnes.Api.Enum.QueueJobStatus.QueueJobStatus Magnes.Api.Object.QueueMetricsBucket
status =
    Object.selectionForField "Enum.QueueJobStatus.QueueJobStatus" "status" [] Magnes.Api.Enum.QueueJobStatus.decoder


createdAtBucket : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.QueueMetricsBucket
createdAtBucket =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAtBucket" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


ranAtBucket : SelectionSet (Maybe Magnes.Api.ScalarCodecs.DateTime) Magnes.Api.Object.QueueMetricsBucket
ranAtBucket =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "ranAtBucket" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


count : SelectionSet Int Magnes.Api.Object.QueueMetricsBucket
count =
    Object.selectionForField "Int" "count" [] Decode.int


latency : SelectionSet (Maybe Magnes.Api.ScalarCodecs.Duration) Magnes.Api.Object.QueueMetricsBucket
latency =
    Object.selectionForField "(Maybe ScalarCodecs.Duration)" "latency" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDuration |> .decoder |> Decode.nullable)
