-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.QueueJobStatusAgg exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.QueueJobStatus
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


value : SelectionSet Magnes.Api.Enum.QueueJobStatus.QueueJobStatus Magnes.Api.Object.QueueJobStatusAgg
value =
    Object.selectionForField "Enum.QueueJobStatus.QueueJobStatus" "value" [] Magnes.Api.Enum.QueueJobStatus.decoder


label : SelectionSet String Magnes.Api.Object.QueueJobStatusAgg
label =
    Object.selectionForField "String" "label" [] Decode.string


count : SelectionSet Int Magnes.Api.Object.QueueJobStatusAgg
count =
    Object.selectionForField "Int" "count" [] Decode.int
