-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.QueueMutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


type alias PurgeJobsRequiredArguments =
    { input : Magnes.Api.InputObject.QueuePurgeJobsInput }


purgeJobs :
    PurgeJobsRequiredArguments
    -> SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.QueueMutation
purgeJobs requiredArgs____ =
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "purgeJobs" [ Argument.required "input" requiredArgs____.input Magnes.Api.InputObject.encodeQueuePurgeJobsInput ] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)


type alias EnqueueReprocessTorrentsBatchOptionalArguments =
    { input : OptionalArgument Magnes.Api.InputObject.QueueEnqueueReprocessTorrentsBatchInput }


enqueueReprocessTorrentsBatch :
    (EnqueueReprocessTorrentsBatchOptionalArguments -> EnqueueReprocessTorrentsBatchOptionalArguments)
    -> SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.QueueMutation
enqueueReprocessTorrentsBatch fillInOptionals____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { input = Absent }

        optionalArgs____ =
            [ Argument.optional "input" filledInOptionals____.input Magnes.Api.InputObject.encodeQueueEnqueueReprocessTorrentsBatchInput ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "enqueueReprocessTorrentsBatch" optionalArgs____ (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)
