-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.QueueJob exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.QueueJobStatus
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


id : SelectionSet Magnes.Api.ScalarCodecs.Id Magnes.Api.Object.QueueJob
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


queue : SelectionSet String Magnes.Api.Object.QueueJob
queue =
    Object.selectionForField "String" "queue" [] Decode.string


status : SelectionSet Magnes.Api.Enum.QueueJobStatus.QueueJobStatus Magnes.Api.Object.QueueJob
status =
    Object.selectionForField "Enum.QueueJobStatus.QueueJobStatus" "status" [] Magnes.Api.Enum.QueueJobStatus.decoder


payload : SelectionSet String Magnes.Api.Object.QueueJob
payload =
    Object.selectionForField "String" "payload" [] Decode.string


priority : SelectionSet Int Magnes.Api.Object.QueueJob
priority =
    Object.selectionForField "Int" "priority" [] Decode.int


retries : SelectionSet Int Magnes.Api.Object.QueueJob
retries =
    Object.selectionForField "Int" "retries" [] Decode.int


maxRetries : SelectionSet Int Magnes.Api.Object.QueueJob
maxRetries =
    Object.selectionForField "Int" "maxRetries" [] Decode.int


runAfter : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.QueueJob
runAfter =
    Object.selectionForField "ScalarCodecs.DateTime" "runAfter" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


ranAt : SelectionSet (Maybe Magnes.Api.ScalarCodecs.DateTime) Magnes.Api.Object.QueueJob
ranAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "ranAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


error : SelectionSet (Maybe String) Magnes.Api.Object.QueueJob
error =
    Object.selectionForField "(Maybe String)" "error" [] (Decode.string |> Decode.nullable)


createdAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.QueueJob
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
