-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.QueueJobsQueryResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


totalCount : SelectionSet Int Magnes.Api.Object.QueueJobsQueryResult
totalCount =
    Object.selectionForField "Int" "totalCount" [] Decode.int


hasNextPage : SelectionSet (Maybe Bool) Magnes.Api.Object.QueueJobsQueryResult
hasNextPage =
    Object.selectionForField "(Maybe Bool)" "hasNextPage" [] (Decode.bool |> Decode.nullable)


items :
    SelectionSet decodesTo Magnes.Api.Object.QueueJob
    -> SelectionSet (List decodesTo) Magnes.Api.Object.QueueJobsQueryResult
items object____ =
    Object.selectionForCompositeField "items" [] object____ (Basics.identity >> Decode.list)


aggregations :
    SelectionSet decodesTo Magnes.Api.Object.QueueJobsAggregations
    -> SelectionSet decodesTo Magnes.Api.Object.QueueJobsQueryResult
aggregations object____ =
    Object.selectionForCompositeField "aggregations" [] object____ Basics.identity
