-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.QueueQuery exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


type alias JobsRequiredArguments =
    { input : Magnes.Api.InputObject.QueueJobsQueryInput }


jobs :
    JobsRequiredArguments
    -> SelectionSet decodesTo Magnes.Api.Object.QueueJobsQueryResult
    -> SelectionSet decodesTo Magnes.Api.Object.QueueQuery
jobs requiredArgs____ object____ =
    Object.selectionForCompositeField "jobs" [ Argument.required "input" requiredArgs____.input Magnes.Api.InputObject.encodeQueueJobsQueryInput ] object____ Basics.identity


type alias MetricsRequiredArguments =
    { input : Magnes.Api.InputObject.QueueMetricsQueryInput }


metrics :
    MetricsRequiredArguments
    -> SelectionSet decodesTo Magnes.Api.Object.QueueMetricsQueryResult
    -> SelectionSet decodesTo Magnes.Api.Object.QueueQuery
metrics requiredArgs____ object____ =
    Object.selectionForCompositeField "metrics" [ Argument.required "input" requiredArgs____.input Magnes.Api.InputObject.encodeQueueMetricsQueryInput ] object____ Basics.identity
