-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.ReleaseYearAgg exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


value : SelectionSet (Maybe Magnes.Api.ScalarCodecs.Year) Magnes.Api.Object.ReleaseYearAgg
value =
    Object.selectionForField "(Maybe ScalarCodecs.Year)" "value" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecYear |> .decoder |> Decode.nullable)


label : SelectionSet String Magnes.Api.Object.ReleaseYearAgg
label =
    Object.selectionForField "String" "label" [] Decode.string


count : SelectionSet Int Magnes.Api.Object.ReleaseYearAgg
count =
    Object.selectionForField "Int" "count" [] Decode.int


isEstimate : SelectionSet Bool Magnes.Api.Object.ReleaseYearAgg
isEstimate =
    Object.selectionForField "Bool" "isEstimate" [] Decode.bool
