-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.Role exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


name : SelectionSet String Magnes.Api.Object.Role
name =
    Object.selectionForField "String" "name" [] Decode.string


core : SelectionSet Bool Magnes.Api.Object.Role
core =
    Object.selectionForField "Bool" "core" [] Decode.bool


permissions :
    SelectionSet decodesTo Magnes.Api.Object.Permission
    -> SelectionSet (List decodesTo) Magnes.Api.Object.Role
permissions object____ =
    Object.selectionForCompositeField "permissions" [] object____ (Basics.identity >> Decode.list)
