-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.Season exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


season : SelectionSet Int Magnes.Api.Object.Season
season =
    Object.selectionForField "Int" "season" [] Decode.int


episodes : SelectionSet (Maybe (List Int)) Magnes.Api.Object.Season
episodes =
    Object.selectionForField "(Maybe (List Int))" "episodes" [] (Decode.int |> Decode.list |> Decode.nullable)
