-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.SelfMutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


type alias RegisterRequiredArguments =
    { input : Magnes.Api.InputObject.RegisterInput }


register :
    RegisterRequiredArguments
    -> SelectionSet decodesTo Magnes.Api.Object.RegisterResult
    -> SelectionSet decodesTo Magnes.Api.Object.SelfMutation
register requiredArgs____ object____ =
    Object.selectionForCompositeField "register" [ Argument.required "input" requiredArgs____.input Magnes.Api.InputObject.encodeRegisterInput ] object____ Basics.identity


type alias LoginRequiredArguments =
    { username : String
    , password : String
    }


login :
    LoginRequiredArguments
    -> SelectionSet decodesTo Magnes.Api.Object.LoginResult
    -> SelectionSet decodesTo Magnes.Api.Object.SelfMutation
login requiredArgs____ object____ =
    Object.selectionForCompositeField "login" [ Argument.required "username" requiredArgs____.username Encode.string, Argument.required "password" requiredArgs____.password Encode.string ] object____ Basics.identity


type alias LoginBrowserRequiredArguments =
    { username : String
    , password : String
    }


loginBrowser :
    LoginBrowserRequiredArguments
    -> SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.SelfMutation
loginBrowser requiredArgs____ =
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "loginBrowser" [ Argument.required "username" requiredArgs____.username Encode.string, Argument.required "password" requiredArgs____.password Encode.string ] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)


logoutBrowser : SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.SelfMutation
logoutBrowser =
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "logoutBrowser" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)


type alias CreateAPIKeyRequiredArguments =
    { input : Magnes.Api.InputObject.CreateAPIKeyInput }


createAPIKey :
    CreateAPIKeyRequiredArguments
    -> SelectionSet decodesTo Magnes.Api.Object.CreateAPIKeyResult
    -> SelectionSet decodesTo Magnes.Api.Object.SelfMutation
createAPIKey requiredArgs____ object____ =
    Object.selectionForCompositeField "createAPIKey" [ Argument.required "input" requiredArgs____.input Magnes.Api.InputObject.encodeCreateAPIKeyInput ] object____ Basics.identity


type alias DeleteAPIKeyRequiredArguments =
    { id : Int }


deleteAPIKey :
    DeleteAPIKeyRequiredArguments
    -> SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.SelfMutation
deleteAPIKey requiredArgs____ =
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "deleteAPIKey" [ Argument.required "id" requiredArgs____.id Encode.int ] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)
