-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.Self exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


user :
    SelectionSet decodesTo Magnes.Api.Object.User
    -> SelectionSet (Maybe decodesTo) Magnes.Api.Object.Self
user object____ =
    Object.selectionForCompositeField "user" [] object____ (Basics.identity >> Decode.nullable)


apiKey :
    SelectionSet decodesTo Magnes.Api.Object.APIKey
    -> SelectionSet (Maybe decodesTo) Magnes.Api.Object.Self
apiKey object____ =
    Object.selectionForCompositeField "apiKey" [] object____ (Basics.identity >> Decode.nullable)


{-| The object actions this identity may exercise right now. For an API key that is
its selected object actions, or the anonymous role's, narrowed by the owning
user's role — because enforcement requires both, so this narrows when the role
does. The selection itself stays visible on `apiKey.permissions`.
-}
permissions :
    SelectionSet decodesTo Magnes.Api.Object.AuthObjectAction
    -> SelectionSet (List decodesTo) Magnes.Api.Object.Self
permissions object____ =
    Object.selectionForCompositeField "permissions" [] object____ (Basics.identity >> Decode.list)
