-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.SelfQuery exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


identity :
    SelectionSet decodesTo Magnes.Api.Object.Self
    -> SelectionSet decodesTo Magnes.Api.Object.SelfQuery
identity object____ =
    Object.selectionForCompositeField "identity" [] object____ Basics.identity


type alias PasswordEntropyRequiredArguments =
    { password : String }


passwordEntropy :
    PasswordEntropyRequiredArguments
    -> SelectionSet decodesTo Magnes.Api.Object.PasswordEntropyResult
    -> SelectionSet decodesTo Magnes.Api.Object.SelfQuery
passwordEntropy requiredArgs____ object____ =
    Object.selectionForCompositeField "passwordEntropy" [ Argument.required "password" requiredArgs____.password Encode.string ] object____ Basics.identity


apiKeys :
    SelectionSet decodesTo Magnes.Api.Object.APIKey
    -> SelectionSet (List decodesTo) Magnes.Api.Object.SelfQuery
apiKeys object____ =
    Object.selectionForCompositeField "apiKeys" [] object____ (Basics.identity >> Decode.list)
