-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.TorrentQuery exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


type alias FilesRequiredArguments =
    { input : Magnes.Api.InputObject.TorrentFilesQueryInput }


files :
    FilesRequiredArguments
    -> SelectionSet decodesTo Magnes.Api.Object.TorrentFilesQueryResult
    -> SelectionSet decodesTo Magnes.Api.Object.TorrentQuery
files requiredArgs____ object____ =
    Object.selectionForCompositeField "files" [ Argument.required "input" requiredArgs____.input Magnes.Api.InputObject.encodeTorrentFilesQueryInput ] object____ Basics.identity


listSources :
    SelectionSet decodesTo Magnes.Api.Object.TorrentListSourcesResult
    -> SelectionSet decodesTo Magnes.Api.Object.TorrentQuery
listSources object____ =
    Object.selectionForCompositeField "listSources" [] object____ Basics.identity


type alias SuggestTagsOptionalArguments =
    { input : OptionalArgument Magnes.Api.InputObject.SuggestTagsQueryInput }


suggestTags :
    (SuggestTagsOptionalArguments -> SuggestTagsOptionalArguments)
    -> SelectionSet decodesTo Magnes.Api.Object.TorrentSuggestTagsResult
    -> SelectionSet decodesTo Magnes.Api.Object.TorrentQuery
suggestTags fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { input = Absent }

        optionalArgs____ =
            [ Argument.optional "input" filledInOptionals____.input Magnes.Api.InputObject.encodeSuggestTagsQueryInput ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "suggestTags" optionalArgs____ object____ Basics.identity


type alias MetricsRequiredArguments =
    { input : Magnes.Api.InputObject.TorrentMetricsQueryInput }


metrics :
    MetricsRequiredArguments
    -> SelectionSet decodesTo Magnes.Api.Object.TorrentMetricsQueryResult
    -> SelectionSet decodesTo Magnes.Api.Object.TorrentQuery
metrics requiredArgs____ object____ =
    Object.selectionForCompositeField "metrics" [ Argument.required "input" requiredArgs____.input Magnes.Api.InputObject.encodeTorrentMetricsQueryInput ] object____ Basics.identity
