-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.TorrentContentSearchResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


totalCount : SelectionSet Int Magnes.Api.Object.TorrentContentSearchResult
totalCount =
    Object.selectionForField "Int" "totalCount" [] Decode.int


totalCountIsEstimate : SelectionSet Bool Magnes.Api.Object.TorrentContentSearchResult
totalCountIsEstimate =
    Object.selectionForField "Bool" "totalCountIsEstimate" [] Decode.bool


{-| hasNextPage is true if there are more results to fetch
-}
hasNextPage : SelectionSet (Maybe Bool) Magnes.Api.Object.TorrentContentSearchResult
hasNextPage =
    Object.selectionForField "(Maybe Bool)" "hasNextPage" [] (Decode.bool |> Decode.nullable)


items :
    SelectionSet decodesTo Magnes.Api.Object.TorrentContent
    -> SelectionSet (List decodesTo) Magnes.Api.Object.TorrentContentSearchResult
items object____ =
    Object.selectionForCompositeField "items" [] object____ (Basics.identity >> Decode.list)


aggregations :
    SelectionSet decodesTo Magnes.Api.Object.TorrentContentAggregations
    -> SelectionSet decodesTo Magnes.Api.Object.TorrentContentSearchResult
aggregations object____ =
    Object.selectionForCompositeField "aggregations" [] object____ Basics.identity
