-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.TorrentMetricsBucket exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


source : SelectionSet String Magnes.Api.Object.TorrentMetricsBucket
source =
    Object.selectionForField "String" "source" [] Decode.string


bucket : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.TorrentMetricsBucket
bucket =
    Object.selectionForField "ScalarCodecs.DateTime" "bucket" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


updated : SelectionSet Bool Magnes.Api.Object.TorrentMetricsBucket
updated =
    Object.selectionForField "Bool" "updated" [] Decode.bool


count : SelectionSet Int Magnes.Api.Object.TorrentMetricsBucket
count =
    Object.selectionForField "Int" "count" [] Decode.int
