-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.Torrent exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.FileType
import Magnes.Api.Enum.FilesStatus
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


infoHash : SelectionSet Magnes.Api.ScalarCodecs.Hash20 Magnes.Api.Object.Torrent
infoHash =
    Object.selectionForField "ScalarCodecs.Hash20" "infoHash" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecHash20 |> .decoder)


name : SelectionSet String Magnes.Api.Object.Torrent
name =
    Object.selectionForField "String" "name" [] Decode.string


size : SelectionSet Int Magnes.Api.Object.Torrent
size =
    Object.selectionForField "Int" "size" [] Decode.int


hasFilesInfo : SelectionSet Bool Magnes.Api.Object.Torrent
hasFilesInfo =
    Object.selectionForField "Bool" "hasFilesInfo" [] Decode.bool


singleFile : SelectionSet (Maybe Bool) Magnes.Api.Object.Torrent
singleFile =
    Object.selectionForField "(Maybe Bool)" "singleFile" [] (Decode.bool |> Decode.nullable)


extension : SelectionSet (Maybe String) Magnes.Api.Object.Torrent
extension =
    Object.selectionForField "(Maybe String)" "extension" [] (Decode.string |> Decode.nullable)


filesStatus : SelectionSet Magnes.Api.Enum.FilesStatus.FilesStatus Magnes.Api.Object.Torrent
filesStatus =
    Object.selectionForField "Enum.FilesStatus.FilesStatus" "filesStatus" [] Magnes.Api.Enum.FilesStatus.decoder


filesCount : SelectionSet (Maybe Int) Magnes.Api.Object.Torrent
filesCount =
    Object.selectionForField "(Maybe Int)" "filesCount" [] (Decode.int |> Decode.nullable)


fileType : SelectionSet (Maybe Magnes.Api.Enum.FileType.FileType) Magnes.Api.Object.Torrent
fileType =
    Object.selectionForField "(Maybe Enum.FileType.FileType)" "fileType" [] (Magnes.Api.Enum.FileType.decoder |> Decode.nullable)


fileTypes : SelectionSet (Maybe (List Magnes.Api.Enum.FileType.FileType)) Magnes.Api.Object.Torrent
fileTypes =
    Object.selectionForField "(Maybe (List Enum.FileType.FileType))" "fileTypes" [] (Magnes.Api.Enum.FileType.decoder |> Decode.list |> Decode.nullable)


files :
    SelectionSet decodesTo Magnes.Api.Object.TorrentFile
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.Torrent
files object____ =
    Object.selectionForCompositeField "files" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


sources :
    SelectionSet decodesTo Magnes.Api.Object.TorrentSourceInfo
    -> SelectionSet (List decodesTo) Magnes.Api.Object.Torrent
sources object____ =
    Object.selectionForCompositeField "sources" [] object____ (Basics.identity >> Decode.list)


seeders : SelectionSet (Maybe Int) Magnes.Api.Object.Torrent
seeders =
    Object.selectionForField "(Maybe Int)" "seeders" [] (Decode.int |> Decode.nullable)


leechers : SelectionSet (Maybe Int) Magnes.Api.Object.Torrent
leechers =
    Object.selectionForField "(Maybe Int)" "leechers" [] (Decode.int |> Decode.nullable)


tagNames : SelectionSet (List String) Magnes.Api.Object.Torrent
tagNames =
    Object.selectionForField "(List String)" "tagNames" [] (Decode.string |> Decode.list)


magnetUri : SelectionSet String Magnes.Api.Object.Torrent
magnetUri =
    Object.selectionForField "String" "magnetUri" [] Decode.string


createdAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.Torrent
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


updatedAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.Torrent
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
