-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.TorrentFilesQueryResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


totalCount : SelectionSet Int Magnes.Api.Object.TorrentFilesQueryResult
totalCount =
    Object.selectionForField "Int" "totalCount" [] Decode.int


hasNextPage : SelectionSet (Maybe Bool) Magnes.Api.Object.TorrentFilesQueryResult
hasNextPage =
    Object.selectionForField "(Maybe Bool)" "hasNextPage" [] (Decode.bool |> Decode.nullable)


items :
    SelectionSet decodesTo Magnes.Api.Object.TorrentFile
    -> SelectionSet (List decodesTo) Magnes.Api.Object.TorrentFilesQueryResult
items object____ =
    Object.selectionForCompositeField "items" [] object____ (Basics.identity >> Decode.list)
