-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.TorrentFile exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.FileType
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


infoHash : SelectionSet Magnes.Api.ScalarCodecs.Hash20 Magnes.Api.Object.TorrentFile
infoHash =
    Object.selectionForField "ScalarCodecs.Hash20" "infoHash" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecHash20 |> .decoder)


index : SelectionSet Int Magnes.Api.Object.TorrentFile
index =
    Object.selectionForField "Int" "index" [] Decode.int


path : SelectionSet String Magnes.Api.Object.TorrentFile
path =
    Object.selectionForField "String" "path" [] Decode.string


extension : SelectionSet (Maybe String) Magnes.Api.Object.TorrentFile
extension =
    Object.selectionForField "(Maybe String)" "extension" [] (Decode.string |> Decode.nullable)


fileType : SelectionSet (Maybe Magnes.Api.Enum.FileType.FileType) Magnes.Api.Object.TorrentFile
fileType =
    Object.selectionForField "(Maybe Enum.FileType.FileType)" "fileType" [] (Magnes.Api.Enum.FileType.decoder |> Decode.nullable)


size : SelectionSet Int Magnes.Api.Object.TorrentFile
size =
    Object.selectionForField "Int" "size" [] Decode.int


createdAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.TorrentFile
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


updatedAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.TorrentFile
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
