-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.TorrentMutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


type alias DeleteRequiredArguments =
    { infoHashes : List Magnes.Api.ScalarCodecs.Hash20 }


delete :
    DeleteRequiredArguments
    -> SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.TorrentMutation
delete requiredArgs____ =
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "delete" [ Argument.required "infoHashes" requiredArgs____.infoHashes ((Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapEncoder .codecHash20) |> Encode.list) ] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)


type alias PutTagsRequiredArguments =
    { infoHashes : List Magnes.Api.ScalarCodecs.Hash20
    , tagNames : List String
    }


putTags :
    PutTagsRequiredArguments
    -> SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.TorrentMutation
putTags requiredArgs____ =
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "putTags" [ Argument.required "infoHashes" requiredArgs____.infoHashes ((Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapEncoder .codecHash20) |> Encode.list), Argument.required "tagNames" requiredArgs____.tagNames (Encode.string |> Encode.list) ] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)


type alias SetTagsRequiredArguments =
    { infoHashes : List Magnes.Api.ScalarCodecs.Hash20
    , tagNames : List String
    }


setTags :
    SetTagsRequiredArguments
    -> SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.TorrentMutation
setTags requiredArgs____ =
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "setTags" [ Argument.required "infoHashes" requiredArgs____.infoHashes ((Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapEncoder .codecHash20) |> Encode.list), Argument.required "tagNames" requiredArgs____.tagNames (Encode.string |> Encode.list) ] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)


type alias DeleteTagsOptionalArguments =
    { infoHashes : OptionalArgument (List Magnes.Api.ScalarCodecs.Hash20)
    , tagNames : OptionalArgument (List String)
    }


deleteTags :
    (DeleteTagsOptionalArguments -> DeleteTagsOptionalArguments)
    -> SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.TorrentMutation
deleteTags fillInOptionals____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { infoHashes = Absent, tagNames = Absent }

        optionalArgs____ =
            [ Argument.optional "infoHashes" filledInOptionals____.infoHashes ((Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapEncoder .codecHash20) |> Encode.list), Argument.optional "tagNames" filledInOptionals____.tagNames (Encode.string |> Encode.list) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "deleteTags" optionalArgs____ (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)


type alias ReprocessRequiredArguments =
    { input : Magnes.Api.InputObject.TorrentReprocessInput }


reprocess :
    ReprocessRequiredArguments
    -> SelectionSet (Maybe Magnes.Api.ScalarCodecs.Void) Magnes.Api.Object.TorrentMutation
reprocess requiredArgs____ =
    Object.selectionForField "(Maybe ScalarCodecs.Void)" "reprocess" [ Argument.required "input" requiredArgs____.input Magnes.Api.InputObject.encodeTorrentReprocessInput ] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecVoid |> .decoder |> Decode.nullable)
