-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.TorrentContentAggregations exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


contentType :
    SelectionSet decodesTo Magnes.Api.Object.ContentTypeAgg
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.TorrentContentAggregations
contentType object____ =
    Object.selectionForCompositeField "contentType" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


torrentSource :
    SelectionSet decodesTo Magnes.Api.Object.TorrentSourceAgg
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.TorrentContentAggregations
torrentSource object____ =
    Object.selectionForCompositeField "torrentSource" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


torrentTag :
    SelectionSet decodesTo Magnes.Api.Object.TorrentTagAgg
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.TorrentContentAggregations
torrentTag object____ =
    Object.selectionForCompositeField "torrentTag" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


torrentFileType :
    SelectionSet decodesTo Magnes.Api.Object.TorrentFileTypeAgg
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.TorrentContentAggregations
torrentFileType object____ =
    Object.selectionForCompositeField "torrentFileType" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


language :
    SelectionSet decodesTo Magnes.Api.Object.LanguageAgg
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.TorrentContentAggregations
language object____ =
    Object.selectionForCompositeField "language" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


genre :
    SelectionSet decodesTo Magnes.Api.Object.GenreAgg
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.TorrentContentAggregations
genre object____ =
    Object.selectionForCompositeField "genre" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


releaseYear :
    SelectionSet decodesTo Magnes.Api.Object.ReleaseYearAgg
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.TorrentContentAggregations
releaseYear object____ =
    Object.selectionForCompositeField "releaseYear" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


videoResolution :
    SelectionSet decodesTo Magnes.Api.Object.VideoResolutionAgg
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.TorrentContentAggregations
videoResolution object____ =
    Object.selectionForCompositeField "videoResolution" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


videoSource :
    SelectionSet decodesTo Magnes.Api.Object.VideoSourceAgg
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.TorrentContentAggregations
videoSource object____ =
    Object.selectionForCompositeField "videoSource" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)
