-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.TorrentContent exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.ContentType
import Magnes.Api.Enum.Video3D
import Magnes.Api.Enum.VideoCodec
import Magnes.Api.Enum.VideoModifier
import Magnes.Api.Enum.VideoResolution
import Magnes.Api.Enum.VideoSource
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


id : SelectionSet Magnes.Api.ScalarCodecs.Id Magnes.Api.Object.TorrentContent
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


infoHash : SelectionSet Magnes.Api.ScalarCodecs.Hash20 Magnes.Api.Object.TorrentContent
infoHash =
    Object.selectionForField "ScalarCodecs.Hash20" "infoHash" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecHash20 |> .decoder)


torrent :
    SelectionSet decodesTo Magnes.Api.Object.Torrent
    -> SelectionSet decodesTo Magnes.Api.Object.TorrentContent
torrent object____ =
    Object.selectionForCompositeField "torrent" [] object____ Basics.identity


contentType : SelectionSet (Maybe Magnes.Api.Enum.ContentType.ContentType) Magnes.Api.Object.TorrentContent
contentType =
    Object.selectionForField "(Maybe Enum.ContentType.ContentType)" "contentType" [] (Magnes.Api.Enum.ContentType.decoder |> Decode.nullable)


contentSource : SelectionSet (Maybe String) Magnes.Api.Object.TorrentContent
contentSource =
    Object.selectionForField "(Maybe String)" "contentSource" [] (Decode.string |> Decode.nullable)


contentId : SelectionSet (Maybe String) Magnes.Api.Object.TorrentContent
contentId =
    Object.selectionForField "(Maybe String)" "contentId" [] (Decode.string |> Decode.nullable)


content :
    SelectionSet decodesTo Magnes.Api.Object.Content
    -> SelectionSet (Maybe decodesTo) Magnes.Api.Object.TorrentContent
content object____ =
    Object.selectionForCompositeField "content" [] object____ (Basics.identity >> Decode.nullable)


title : SelectionSet String Magnes.Api.Object.TorrentContent
title =
    Object.selectionForField "String" "title" [] Decode.string


languages :
    SelectionSet decodesTo Magnes.Api.Object.LanguageInfo
    -> SelectionSet (Maybe (List decodesTo)) Magnes.Api.Object.TorrentContent
languages object____ =
    Object.selectionForCompositeField "languages" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


episodes :
    SelectionSet decodesTo Magnes.Api.Object.Episodes
    -> SelectionSet (Maybe decodesTo) Magnes.Api.Object.TorrentContent
episodes object____ =
    Object.selectionForCompositeField "episodes" [] object____ (Basics.identity >> Decode.nullable)


videoResolution : SelectionSet (Maybe Magnes.Api.Enum.VideoResolution.VideoResolution) Magnes.Api.Object.TorrentContent
videoResolution =
    Object.selectionForField "(Maybe Enum.VideoResolution.VideoResolution)" "videoResolution" [] (Magnes.Api.Enum.VideoResolution.decoder |> Decode.nullable)


videoSource : SelectionSet (Maybe Magnes.Api.Enum.VideoSource.VideoSource) Magnes.Api.Object.TorrentContent
videoSource =
    Object.selectionForField "(Maybe Enum.VideoSource.VideoSource)" "videoSource" [] (Magnes.Api.Enum.VideoSource.decoder |> Decode.nullable)


videoCodec : SelectionSet (Maybe Magnes.Api.Enum.VideoCodec.VideoCodec) Magnes.Api.Object.TorrentContent
videoCodec =
    Object.selectionForField "(Maybe Enum.VideoCodec.VideoCodec)" "videoCodec" [] (Magnes.Api.Enum.VideoCodec.decoder |> Decode.nullable)


video3d : SelectionSet (Maybe Magnes.Api.Enum.Video3D.Video3D) Magnes.Api.Object.TorrentContent
video3d =
    Object.selectionForField "(Maybe Enum.Video3D.Video3D)" "video3d" [] (Magnes.Api.Enum.Video3D.decoder |> Decode.nullable)


videoModifier : SelectionSet (Maybe Magnes.Api.Enum.VideoModifier.VideoModifier) Magnes.Api.Object.TorrentContent
videoModifier =
    Object.selectionForField "(Maybe Enum.VideoModifier.VideoModifier)" "videoModifier" [] (Magnes.Api.Enum.VideoModifier.decoder |> Decode.nullable)


releaseGroup : SelectionSet (Maybe String) Magnes.Api.Object.TorrentContent
releaseGroup =
    Object.selectionForField "(Maybe String)" "releaseGroup" [] (Decode.string |> Decode.nullable)


seeders : SelectionSet (Maybe Int) Magnes.Api.Object.TorrentContent
seeders =
    Object.selectionForField "(Maybe Int)" "seeders" [] (Decode.int |> Decode.nullable)


leechers : SelectionSet (Maybe Int) Magnes.Api.Object.TorrentContent
leechers =
    Object.selectionForField "(Maybe Int)" "leechers" [] (Decode.int |> Decode.nullable)


publishedAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.TorrentContent
publishedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "publishedAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


createdAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.TorrentContent
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


updatedAt : SelectionSet Magnes.Api.ScalarCodecs.DateTime Magnes.Api.Object.TorrentContent
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Magnes.Api.ScalarCodecs.codecs |> Magnes.Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
