-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.VideoSourceAgg exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.VideoSource
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


value : SelectionSet (Maybe Magnes.Api.Enum.VideoSource.VideoSource) Magnes.Api.Object.VideoSourceAgg
value =
    Object.selectionForField "(Maybe Enum.VideoSource.VideoSource)" "value" [] (Magnes.Api.Enum.VideoSource.decoder |> Decode.nullable)


label : SelectionSet String Magnes.Api.Object.VideoSourceAgg
label =
    Object.selectionForField "String" "label" [] Decode.string


count : SelectionSet Int Magnes.Api.Object.VideoSourceAgg
count =
    Object.selectionForField "Int" "count" [] Decode.int


isEstimate : SelectionSet Bool Magnes.Api.Object.VideoSourceAgg
isEstimate =
    Object.selectionForField "Bool" "isEstimate" [] Decode.bool
