-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.VideoResolutionAgg exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.Enum.VideoResolution
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


value : SelectionSet (Maybe Magnes.Api.Enum.VideoResolution.VideoResolution) Magnes.Api.Object.VideoResolutionAgg
value =
    Object.selectionForField "(Maybe Enum.VideoResolution.VideoResolution)" "value" [] (Magnes.Api.Enum.VideoResolution.decoder |> Decode.nullable)


label : SelectionSet String Magnes.Api.Object.VideoResolutionAgg
label =
    Object.selectionForField "String" "label" [] Decode.string


count : SelectionSet Int Magnes.Api.Object.VideoResolutionAgg
count =
    Object.selectionForField "Int" "count" [] Decode.int


isEstimate : SelectionSet Bool Magnes.Api.Object.VideoResolutionAgg
isEstimate =
    Object.selectionForField "Bool" "isEstimate" [] Decode.bool
