-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Magnes.Api.Object.Worker exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Magnes.Api.InputObject
import Magnes.Api.Interface
import Magnes.Api.Object
import Magnes.Api.Scalar
import Magnes.Api.ScalarCodecs
import Magnes.Api.Union


key : SelectionSet String Magnes.Api.Object.Worker
key =
    Object.selectionForField "String" "key" [] Decode.string


started : SelectionSet Bool Magnes.Api.Object.Worker
started =
    Object.selectionForField "Bool" "started" [] Decode.bool
